worker_processes  1;

pid /var/run/nginx.pid;

events {

    worker_connections   1024;
    
}

http {

    keepalive_timeout   65;
    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    server_tokens       off;
    
    proxy_no_cache      1;
    proxy_cache_bypass  1;

    default_type        application/octet-stream;
    
    include             /usr/local/openresty/nginx/conf/mime.types;
    include             /etc/nginx/conf.d/*.conf;

    log_format          main '[$time_iso8601] [ess-smart-web-api-nginx]: REMOTE_ADDR:$remote_addr REMOTE_USER:$remote_user HOST:$host REQUEST:$request STATUS:$status BODY_BYTES_SENT:$body_bytes_sent HTTP_REFERER:$http_referer USER_AGENT:$http_user_agent X_FORWARD:$http_x_forwarded_for UPSTREAM_ADDR:$upstream_addr UPSTREAM_STATUS:$upstream_status UPSTREAM_CACHE_STATUS:$upstream_cache_status';
    access_log          /dev/stdout main;
    error_log           /dev/stderr warn;

}