BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  IF to_jsonb(NEW) ? 'updated_at' THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object('updated_at', now()));
  ELSIF to_jsonb(NEW) ? '_updated_at' THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object('_updated_at', now()));
  ELSIF to_jsonb(NEW) ? (TG_TABLE_NAME || '_updated_at') THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_TABLE_NAME || '_updated_at', now()));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_state_code
  ON state(code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_state_name
  ON state(name);

INSERT INTO state (id, code, name) VALUES
  (1, 'AK', 'Alaska'),
  (2, 'AL', 'Alabama'),
  (3, 'AR', 'Arkansas'),
  (4, 'AZ', 'Arizona'),
  (5, 'CA', 'California'),
  (6, 'CO', 'Colorado'),
  (7, 'CT', 'Connecticut'),
  (8, 'DC', 'District of Columbia'),
  (9, 'DE', 'Delaware'),
  (10, 'FL', 'Florida'),
  (11, 'GA', 'Georgia'),
  (12, 'HI', 'Hawaii'),
  (13, 'IA', 'Iowa'),
  (14, 'ID', 'Idaho'),
  (15, 'IL', 'Illinois'),
  (16, 'IN', 'Indiana'),
  (17, 'KS', 'Kansas'),
  (18, 'KY', 'Kentucky'),
  (19, 'LA', 'Louisiana'),
  (20, 'MA', 'Massachusetts'),
  (21, 'MD', 'Maryland'),
  (22, 'ME', 'Maine'),
  (23, 'MI', 'Michigan'),
  (24, 'MN', 'Minnesota'),
  (25, 'MO', 'Missouri'),
  (26, 'MS', 'Mississippi'),
  (27, 'MT', 'Montana'),
  (28, 'NC', 'North Carolina'),
  (29, 'ND', 'North Dakota'),
  (30, 'NE', 'Nebraska'),
  (31, 'NH', 'New Hampshire'),
  (32, 'NJ', 'New Jersey'),
  (33, 'NM', 'New Mexico'),
  (34, 'NV', 'Nevada'),
  (35, 'NY', 'New York'),
  (36, 'OH', 'Ohio'),
  (37, 'OK', 'Oklahoma'),
  (38, 'OR', 'Oregon'),
  (39, 'PA', 'Pennsylvania'),
  (40, 'RI', 'Rhode Island'),
  (41, 'SC', 'South Carolina'),
  (42, 'SD', 'South Dakota'),
  (43, 'TN', 'Tennessee'),
  (44, 'TX', 'Texas'),
  (45, 'UT', 'Utah'),
  (46, 'VA', 'Virginia'),
  (47, 'VT', 'Vermont'),
  (48, 'WA', 'Washington'),
  (49, 'WI', 'Wisconsin'),
  (50, 'WV', 'West Virginia'),
  (51, 'WY', 'Wyoming')
ON CONFLICT (id) DO UPDATE
SET code = EXCLUDED.code,
    name = EXCLUDED.name;

CREATE TABLE IF NOT EXISTS timezone (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_timezone_name
  ON timezone(name);

INSERT INTO timezone (name) VALUES
  ('(GMT) Casablanca, Monrovia'),
  ('(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'),
  ('(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna'),
  ('(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague'),
  ('(GMT+01:00) Brussels, Copenhagen, Madrid, Paris'),
  ('(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb'),
  ('(GMT+01:00) West Central Africa'),
  ('(GMT+02:00) Athens, Istanbul, Minsk'),
  ('(GMT+02:00) Bucharest'),
  ('(GMT+02:00) Cairo'),
  ('(GMT+02:00) Harare, Pretoria'),
  ('(GMT+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius'),
  ('(GMT+02:00) Jerusalem'),
  ('(GMT+03:00) Baghdad'),
  ('(GMT+03:00) Kuwait, Riyadh'),
  ('(GMT+03:00) Moscow, St. Petersburg, Volgograd'),
  ('(GMT+03:00) Nairobi'),
  ('(GMT+03:30) Tehran'),
  ('(GMT+04:00) Abu Dhabi, Muscat'),
  ('(GMT+04:00) Baku, Tbilisi, Yerevan'),
  ('(GMT+04:30) Kabul'),
  ('(GMT+05:00) Ekaterinburg'),
  ('(GMT+05:00) Islamabad, Karachi, Tashkent'),
  ('(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi'),
  ('(GMT+05:45) Kathmandu'),
  ('(GMT+06:00) Almaty, Novosibirsk'),
  ('(GMT+06:00) Astana, Dhaka'),
  ('(GMT+06:00) Sri Jayawardenepura'),
  ('(GMT+06:30) Yangon Rangoon'),
  ('(GMT+07:00) Bangkok, Hanoi, Jakarta'),
  ('(GMT+07:00) Krasnoyarsk'),
  ('(GMT+08:00) Beijing, Chongqing, Hong Kong SAR, Urumqi'),
  ('(GMT+08:00) Irkutsk, Ulaanbaatar'),
  ('(GMT+08:00) Kuala Lumpur, Singapore'),
  ('(GMT+08:00) Perth'),
  ('(GMT+08:00) Taipei'),
  ('(GMT+09:00) Osaka, Sapporo, Tokyo'),
  ('(GMT+09:00) Seoul'),
  ('(GMT+09:00) Yakutsk'),
  ('(GMT+09:30) Adelaide'),
  ('(GMT+09:30) Darwin'),
  ('(GMT+10:00) Brisbane'),
  ('(GMT+10:00) Canberra, Melbourne, Sydney'),
  ('(GMT+10:00) Guam, Port Moresby'),
  ('(GMT+10:00) Hobart'),
  ('(GMT+10:00) Vladivostok'),
  ('(GMT+11:00) Magadan, Solomon Islands, New Caledonia'),
  ('(GMT+12:00) Auckland, Wellington'),
  ('(GMT+12:00) Fiji Islands, Kamchatka, Marshall Islands'),
  ('(GMT+13:00) Nuku''alofa'),
  ('(GMT-01:00) Azores'),
  ('(GMT-01:00) Cape Verde Islands'),
  ('(GMT-02:00) Mid-Atlantic'),
  ('(GMT-03:00) Brasilia'),
  ('(GMT-03:00) Buenos Aires, Georgetown'),
  ('(GMT-03:00) Greenland'),
  ('(GMT-03:30) Newfoundland and Labrador'),
  ('(GMT-04:00) Atlantic Time (Canada)'),
  ('(GMT-04:00) Caracas, La Paz'),
  ('(GMT-04:00) Santiago'),
  ('(GMT-05:00) Bogota, Lima, Quito'),
  ('(GMT-05:00) Eastern Time (US and Canada)'),
  ('(GMT-05:00) Indiana (East)'),
  ('(GMT-06:00) Central America'),
  ('(GMT-06:00) Central Time (US and Canada)'),
  ('(GMT-06:00) Guadalajara, Mexico City, Monterrey'),
  ('(GMT-06:00) Saskatchewan'),
  ('(GMT-07:00) Arizona'),
  ('(GMT-07:00) Chihuahua, La Paz, Mazatlan'),
  ('(GMT-07:00) Mountain Time (US and Canada)'),
  ('(GMT-08:00) Pacific Time (US and Canada); Tijuana'),
  ('(GMT-09:00) Alaska'),
  ('(GMT-10:00) Hawaii'),
  ('(GMT-11:00) Midway Island, Samoa'),
  ('(GMT-12:00) International Date Line West')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS companytype (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::bigint,
  guid UUID NOT NULL DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  risk TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_companytype_tenant_guid
  ON companytype(tenant_id, guid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_companytype_tenant_name
  ON companytype(tenant_id, name);
CREATE INDEX IF NOT EXISTS ix_companytype_tenant
  ON companytype(tenant_id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_companytype_updated_at') THEN
    CREATE TRIGGER trg_companytype_updated_at
      BEFORE UPDATE ON companytype
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE companytype ENABLE ROW LEVEL SECURITY;
ALTER TABLE companytype FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_companytype_tenant ON companytype;
CREATE POLICY p_companytype_tenant ON companytype
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS jobtype (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::bigint,
  guid UUID NOT NULL DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_jobtype_tenant_guid
  ON jobtype(tenant_id, guid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_jobtype_tenant_name
  ON jobtype(tenant_id, name);
CREATE INDEX IF NOT EXISTS ix_jobtype_tenant
  ON jobtype(tenant_id);
CREATE INDEX IF NOT EXISTS ix_jobtype_tenant_active
  ON jobtype(tenant_id, active);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_jobtype_updated_at') THEN
    CREATE TRIGGER trg_jobtype_updated_at
      BEFORE UPDATE ON jobtype
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE jobtype ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobtype FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_jobtype_tenant ON jobtype;
CREATE POLICY p_jobtype_tenant ON jobtype
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS company (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::bigint,
  guid UUID NOT NULL DEFAULT gen_random_uuid(),
  active BOOLEAN NOT NULL DEFAULT true,
  name TEXT NOT NULL,
  address_line_1 TEXT,
  address_line_2 TEXT,
  city TEXT,
  company_policy TEXT,
  fax TEXT,
  phone TEXT,
  state_id BIGINT REFERENCES state(id),
  unemployment_policy TEXT,
  url TEXT,
  company_type_id BIGINT REFERENCES companytype(id),
  zip TEXT,
  email CITEXT,
  main_company_id BIGINT REFERENCES company(id),
  description TEXT,
  vendor_code TEXT,
  tax_id TEXT,
  liaison TEXT,
  legacy_key TEXT,
  premium INTEGER,
  safety_policy TEXT,
  timezone_id BIGINT REFERENCES timezone(id),
  demo BOOLEAN,
  contact_name TEXT,
  naics_code TEXT,
  product_code TEXT,
  company_number TEXT,
  record_group TEXT,
  geo_code TEXT,
  contract_number TEXT,
  joined_at DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_company_tenant_guid
  ON company(tenant_id, guid);
CREATE INDEX IF NOT EXISTS ix_company_tenant_name
  ON company(tenant_id, name);
CREATE INDEX IF NOT EXISTS ix_company_tenant_active
  ON company(tenant_id, active);
CREATE INDEX IF NOT EXISTS ix_company_tenant_state_id
  ON company(tenant_id, state_id);
CREATE INDEX IF NOT EXISTS ix_company_tenant_company_type_id
  ON company(tenant_id, company_type_id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_company_updated_at') THEN
    CREATE TRIGGER trg_company_updated_at
      BEFORE UPDATE ON company
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE company ENABLE ROW LEVEL SECURITY;
ALTER TABLE company FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_company_tenant ON company;
CREATE POLICY p_company_tenant ON company
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::bigint,
  guid UUID NOT NULL DEFAULT gen_random_uuid(),
  tour_read BOOLEAN,
  system_access BOOLEAN,
  active BOOLEAN NOT NULL DEFAULT true,
  admin_access BOOLEAN,
  company_id BIGINT REFERENCES company(id),
  recorded_at TIMESTAMPTZ,
  date_of_birth DATE,
  email CITEXT,
  first_name TEXT,
  last_name TEXT,
  middle_name TEXT,
  mobile_phone TEXT,
  pager TEXT,
  password TEXT,
  phone TEXT,
  job_type_id BIGINT REFERENCES jobtype(id),
  username TEXT,
  supervisor_user_id BIGINT REFERENCES users(id),
  foreman_user_id BIGINT REFERENCES users(id),
  notes TEXT,
  hire_date DATE,
  rehire_date DATE,
  last_work_date DATE,
  termination_date DATE,
  sex TEXT,
  employee_number TEXT,
  pcode TEXT,
  last_seen_at TIMESTAMPTZ,
  last_module TEXT,
  last_action TEXT,
  last_page TEXT,
  last_wizard TEXT,
  timezone_id BIGINT REFERENCES timezone(id),
  address_line_1 TEXT,
  city TEXT,
  state_id BIGINT REFERENCES state(id),
  zip TEXT,
  ssn TEXT,
  password_changed_at TIMESTAMPTZ,
  terms_accepted BOOLEAN,
  password_changed_count INTEGER,
  demo BOOLEAN,
  status TEXT,
  reason TEXT,
  occupation TEXT,
  salary_amount NUMERIC(14,2),
  salary_rate NUMERIC(14,2),
  system_id TEXT,
  auth_level INTEGER,
  sys_id TEXT,
  site TEXT,
  legacy_user_id TEXT,
  ets_admin BOOLEAN NOT NULL DEFAULT false,
  supervisor_1027_user_id BIGINT,
  department_1042 TEXT,
  supervisor_1042_user_id_2 BIGINT,
  supervisor_1042_user_id_3 BIGINT,
  supervisor_1042_user_id_1 BIGINT,
  wc_code TEXT,
  wc_description TEXT,
  messenger_app TEXT,
  messenger_account TEXT,
  covid_check BOOLEAN,
  honorific TEXT,
  pin_code TEXT,
  codes JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_tenant_guid
  ON users(tenant_id, guid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_tenant_email
  ON users(tenant_id, email)
  WHERE email IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_users_tenant_company_id
  ON users(tenant_id, company_id);
CREATE INDEX IF NOT EXISTS ix_users_tenant_job_type_id
  ON users(tenant_id, job_type_id);
CREATE INDEX IF NOT EXISTS ix_users_tenant_active
  ON users(tenant_id, active);
CREATE INDEX IF NOT EXISTS ix_users_tenant_system_access
  ON users(tenant_id, system_access);
CREATE INDEX IF NOT EXISTS ix_users_tenant_admin_access
  ON users(tenant_id, admin_access);
CREATE INDEX IF NOT EXISTS ix_users_tenant_mobile_phone
  ON users(tenant_id, mobile_phone);
CREATE INDEX IF NOT EXISTS ix_users_tenant_phone
  ON users(tenant_id, phone);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_users_updated_at') THEN
    CREATE TRIGGER trg_users_updated_at
      BEFORE UPDATE ON users
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_users_tenant ON users;
CREATE POLICY p_users_tenant ON users
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::bigint,
  guid UUID NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id BIGINT REFERENCES users(id),
  recorded_at TIMESTAMPTZ,
  active BOOLEAN NOT NULL DEFAULT true,
  address_line_1 TEXT,
  address_line_2 TEXT,
  city TEXT,
  phone TEXT,
  fax TEXT,
  email CITEXT,
  company_id BIGINT REFERENCES company(id),
  contractor_company_id BIGINT,
  start_date TIMESTAMPTZ,
  end_date TIMESTAMPTZ,
  description TEXT,
  info TEXT,
  name TEXT NOT NULL,
  project_number TEXT,
  project_status_id BIGINT,
  state_id BIGINT REFERENCES state(id),
  url TEXT,
  contract_value NUMERIC(14,2),
  zip TEXT,
  ocip TEXT,
  medfac_8 INTEGER,
  medfac_24 INTEGER,
  gl_ocip TEXT,
  gl_bid TEXT,
  wc_ocip TEXT,
  wc_bid TEXT,
  status TEXT,
  year TEXT,
  pc TEXT,
  rate TEXT,
  type TEXT,
  detailer_user_id BIGINT REFERENCES users(id),
  estimator_user_id BIGINT REFERENCES users(id),
  salesperson_user_id BIGINT REFERENCES users(id),
  sov TEXT,
  estimate_number TEXT,
  estimate_weight TEXT,
  fi_unit TEXT,
  average_rate TEXT,
  c_amount TEXT,
  detail_unit TEXT,
  margin TEXT,
  g_amount TEXT,
  g_man_hours TEXT,
  g_rate TEXT,
  letter_sent_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  contact_id BIGINT,
  pt_vendor_company_id BIGINT,
  sub TEXT,
  ve TEXT,
  payroll TEXT,
  applied_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  pin_nam TEXT,
  pin_cost TEXT,
  pin_margin TEXT,
  pin_pr TEXT,
  pcode TEXT,
  ohp TEXT,
  project_manager_user_id BIGINT REFERENCES users(id),
  project_superintendent_user_id BIGINT REFERENCES users(id),
  project_safety_rep_user_id BIGINT REFERENCES users(id),
  tar INTEGER,
  subcontractor_company_id BIGINT,
  demo BOOLEAN,
  naics_code TEXT,
  industry_description TEXT,
  size TEXT,
  avg TEXT,
  geo_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_projects_tenant_guid
  ON projects(tenant_id, guid);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_owner_user_id
  ON projects(tenant_id, owner_user_id);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_company_id
  ON projects(tenant_id, company_id);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_name
  ON projects(tenant_id, name);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_project_number
  ON projects(tenant_id, project_number);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_active
  ON projects(tenant_id, active);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_projects_updated_at') THEN
    CREATE TRIGGER trg_projects_updated_at
      BEFORE UPDATE ON projects
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_projects_tenant ON projects;
CREATE POLICY p_projects_tenant ON projects
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS projectsaccess (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::bigint,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_projectsaccess_tenant_project_user
  ON projectsaccess(tenant_id, project_id, user_id);
CREATE INDEX IF NOT EXISTS ix_projectsaccess_tenant_user
  ON projectsaccess(tenant_id, user_id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_projectsaccess_updated_at') THEN
    CREATE TRIGGER trg_projectsaccess_updated_at
      BEFORE UPDATE ON projectsaccess
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE projectsaccess ENABLE ROW LEVEL SECURITY;
ALTER TABLE projectsaccess FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_projectsaccess_tenant ON projectsaccess;
CREATE POLICY p_projectsaccess_tenant ON projectsaccess
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::bigint,
  guid UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT,
  principal_guid UUID,
  occurred_at TIMESTAMPTZ,
  event TEXT,
  module TEXT,
  record_id BIGINT,
  table_name TEXT,
  text TEXT,
  timezone_name TEXT,
  user_ip TEXT,
  recipients TEXT,
  subject TEXT,
  body TEXT,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  files JSONB,
  urls JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_events_tenant_created
  ON events(tenant_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_events_tenant_guid
  ON events(tenant_id, guid);
CREATE INDEX IF NOT EXISTS ix_events_tenant_event
  ON events(tenant_id, event, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_events_tenant_principal_guid
  ON events(tenant_id, principal_guid, created_at DESC)
  WHERE principal_guid IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_events_tenant_module
  ON events(tenant_id, module, created_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_events_updated_at') THEN
    CREATE TRIGGER trg_events_updated_at
      BEFORE UPDATE ON events
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_events_tenant ON events;
CREATE POLICY p_events_tenant ON events
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS mails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::bigint,
  guid UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT,
  sent_at TIMESTAMPTZ,
  timezone_name TEXT,
  from_address TEXT,
  to_addresses TEXT,
  cc_addresses TEXT,
  bcc_addresses TEXT,
  subject TEXT,
  body TEXT,
  sender_name TEXT,
  files JSONB,
  urls JSONB,
  target_table TEXT,
  target_record_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_mails_tenant_user
  ON mails(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS ix_mails_tenant_target_record_id
  ON mails(tenant_id, target_record_id);
CREATE INDEX IF NOT EXISTS ix_mails_tenant_sent_at
  ON mails(tenant_id, sent_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_mails_updated_at') THEN
    CREATE TRIGGER trg_mails_updated_at
      BEFORE UPDATE ON mails
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE mails ENABLE ROW LEVEL SECURITY;
ALTER TABLE mails FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_mails_tenant ON mails;
CREATE POLICY p_mails_tenant ON mails
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS public_code (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  code TEXT NOT NULL,
  kind TEXT NOT NULL,
  resource_id BIGINT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_public_code_tenant_code
  ON public_code(tenant_id, code);
CREATE INDEX IF NOT EXISTS ix_public_code_tenant
  ON public_code(tenant_id);
CREATE INDEX IF NOT EXISTS ix_public_code_expires
  ON public_code(expires_at)
  WHERE expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_public_code_resource
  ON public_code(resource_id)
  WHERE resource_id IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_public_code_updated_at') THEN
    CREATE TRIGGER trg_public_code_updated_at
      BEFORE UPDATE ON public_code
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS notification_template (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT,
  kind TEXT NOT NULL,
  key TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'default',
  subject TEXT,
  html TEXT,
  text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_template_global
  ON notification_template(kind, key, locale)
  WHERE tenant_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_template_tenant
  ON notification_template(tenant_id, kind, key, locale)
  WHERE tenant_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_notification_template_tenant
  ON notification_template(tenant_id);
CREATE INDEX IF NOT EXISTS ix_notification_template_key
  ON notification_template(kind, key);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_notification_template_updated_at') THEN
    CREATE TRIGGER trg_notification_template_updated_at
      BEFORE UPDATE ON notification_template
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

INSERT INTO notification_template
(tenant_id, kind, key, locale, subject, html, text)
SELECT
  NULL, 'email', 'otp', 'default',
  'Your verification code',
  '<p>Your code is <strong>{{ code }}</strong>.</p><p>It is valid for {{ ttl }} minutes.</p>',
  'Your code {{ code }}, valid for {{ ttl }} minutes.'
WHERE NOT EXISTS (
  SELECT 1
    FROM notification_template
   WHERE tenant_id IS NULL
     AND kind = 'email'
     AND key = 'otp'
     AND locale = 'default'
);

INSERT INTO notification_template
(tenant_id, kind, key, locale, subject, html, text)
SELECT
  NULL, 'sms', 'otp', 'default',
  NULL,
  NULL,
  'Your code {{ code }}, valid for {{ ttl }} minutes.'
WHERE NOT EXISTS (
  SELECT 1
    FROM notification_template
   WHERE tenant_id IS NULL
     AND kind = 'sms'
     AND key = 'otp'
     AND locale = 'default'
);

CREATE TABLE IF NOT EXISTS ps_model (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid               UUID NOT NULL DEFAULT gen_random_uuid(),
  model_id           TEXT NOT NULL,
  model_key          TEXT NOT NULL,
  storage_key        TEXT,
  display_name       TEXT NOT NULL,
  description        TEXT,
  source_type        TEXT NOT NULL DEFAULT 'managed',
  status             TEXT NOT NULL DEFAULT 'draft',
  version            BIGINT NOT NULL DEFAULT 1,
  published_version  BIGINT NOT NULL DEFAULT 0,
  structure_version  BIGINT NOT NULL DEFAULT 1,
  definition_json    JSONB NOT NULL DEFAULT '{}'::jsonb,
  model_locked       BOOLEAN NOT NULL DEFAULT false,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ps_model_model_id
  ON ps_model(model_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ps_model_guid
  ON ps_model(guid);
CREATE INDEX IF NOT EXISTS ix_ps_model_updated_at
  ON ps_model(updated_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_ps_model_updated_at') THEN
    CREATE TRIGGER trg_ps_model_updated_at
      BEFORE UPDATE ON ps_model
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS ps_view (
  id                                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid                                 UUID NOT NULL DEFAULT gen_random_uuid(),
  model_id                             TEXT NOT NULL REFERENCES ps_model(model_id) ON DELETE CASCADE,
  view_id                              TEXT NOT NULL,
  view_key                             TEXT NOT NULL,
  display_name                         TEXT NOT NULL,
  description                          TEXT,
  view_type                            TEXT NOT NULL DEFAULT 'form',
  is_default                           BOOLEAN NOT NULL DEFAULT false,
  is_active                            BOOLEAN NOT NULL DEFAULT true,
  status                               TEXT NOT NULL DEFAULT 'draft',
  version                              BIGINT NOT NULL DEFAULT 1,
  published_version                    BIGINT NOT NULL DEFAULT 0,
  last_aligned_model_structure_version BIGINT NOT NULL DEFAULT 1,
  definition_json                      JSONB NOT NULL DEFAULT '{}'::jsonb,
  published_artifacts_json             JSONB NOT NULL DEFAULT '{}'::jsonb,
  view_locked                          BOOLEAN NOT NULL DEFAULT false,
  created_at                           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ps_view_model_view_id
  ON ps_view(model_id, view_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ps_view_guid
  ON ps_view(guid);
CREATE INDEX IF NOT EXISTS ix_ps_view_model_id
  ON ps_view(model_id);
CREATE INDEX IF NOT EXISTS ix_ps_view_updated_at
  ON ps_view(updated_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_ps_view_updated_at') THEN
    CREATE TRIGGER trg_ps_view_updated_at
      BEFORE UPDATE ON ps_view
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

COMMIT;
