BEGIN;

CREATE TABLE IF NOT EXISTS ps_runtime_saved_filter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid UUID NOT NULL DEFAULT gen_random_uuid(),
  principal_id UUID NOT NULL,
  surface_id TEXT NOT NULL,
  label TEXT NOT NULL,
  quick_filters JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ps_runtime_saved_filter_guid_key UNIQUE (guid),
  CONSTRAINT ps_runtime_saved_filter_surface_chk CHECK (btrim(surface_id) <> ''),
  CONSTRAINT ps_runtime_saved_filter_label_chk CHECK (btrim(label) <> ''),
  CONSTRAINT ps_runtime_saved_filter_quick_filters_chk CHECK (jsonb_typeof(quick_filters) = 'array')
);

CREATE INDEX IF NOT EXISTS ix_ps_runtime_saved_filter_principal_surface
  ON ps_runtime_saved_filter(principal_id, surface_id, created_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_ps_runtime_saved_filter_updated_at') THEN
    CREATE TRIGGER trg_ps_runtime_saved_filter_updated_at
      BEFORE UPDATE ON ps_runtime_saved_filter
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

COMMIT;
