BEGIN;

CREATE TABLE IF NOT EXISTS ps_runtime_favorite (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid UUID NOT NULL DEFAULT gen_random_uuid(),
  principal_id UUID NOT NULL,
  surface_id TEXT NOT NULL,
  model_id TEXT NOT NULL,
  view_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ps_runtime_favorite_guid_key UNIQUE (guid),
  CONSTRAINT ps_runtime_favorite_principal_surface_key UNIQUE (principal_id, surface_id),
  CONSTRAINT ps_runtime_favorite_surface_chk CHECK (btrim(surface_id) <> ''),
  CONSTRAINT ps_runtime_favorite_model_chk CHECK (btrim(model_id) <> ''),
  CONSTRAINT ps_runtime_favorite_view_chk CHECK (btrim(view_id) <> '')
);

CREATE INDEX IF NOT EXISTS ix_ps_runtime_favorite_principal_created
  ON ps_runtime_favorite(principal_id, created_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_ps_runtime_favorite_updated_at') THEN
    CREATE TRIGGER trg_ps_runtime_favorite_updated_at
      BEFORE UPDATE ON ps_runtime_favorite
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

COMMIT;
