BEGIN;

CREATE TABLE IF NOT EXISTS ps_navigation_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid UUID NOT NULL DEFAULT gen_random_uuid(),
  config_key TEXT NOT NULL DEFAULT 'default',
  version BIGINT NOT NULL DEFAULT 1,
  definition_json JSONB NOT NULL DEFAULT '{"schemaVersion":1,"appMenu":[],"utilityRail":[]}'::jsonb,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ps_navigation_config_guid_key UNIQUE (guid),
  CONSTRAINT ps_navigation_config_key_key UNIQUE (config_key),
  CONSTRAINT ps_navigation_config_key_chk CHECK (btrim(config_key) <> ''),
  CONSTRAINT ps_navigation_config_version_chk CHECK (version > 0),
  CONSTRAINT ps_navigation_config_definition_chk CHECK (jsonb_typeof(definition_json) = 'object')
);

CREATE INDEX IF NOT EXISTS ix_ps_navigation_config_updated_at
  ON ps_navigation_config(updated_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_ps_navigation_config_updated_at') THEN
    CREATE TRIGGER trg_ps_navigation_config_updated_at
      BEFORE UPDATE ON ps_navigation_config
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

COMMIT;
