BEGIN;

-- Seed project industry reference tables and expose Projects as a static
-- Form Builder model. Existing authored metadata wins; inserts below are
-- intentionally non-destructive.

CREATE TABLE IF NOT EXISTS industry_size (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_industry_size_name
  ON industry_size(name);

INSERT INTO industry_size (id, name)
VALUES
  (1, 'has < 20 employees'),
  (2, 'has 20-249 employees'),
  (3, 'has 250+ employees')
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name;

SELECT setval(
  pg_get_serial_sequence('industry_size', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 1) FROM industry_size), 1),
  true
);

CREATE TABLE IF NOT EXISTS industry_type (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_industry_type_name
  ON industry_type(name);

INSERT INTO industry_type (id, name)
VALUES
  (1, 'is not a government entity'),
  (2, 'is a State Government entity'),
  (3, 'is a Local Government entity')
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name;

SELECT setval(
  pg_get_serial_sequence('industry_type', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 1) FROM industry_type), 1),
  true
);

ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS industry_size_id BIGINT;

ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS industry_type_id BIGINT;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
      FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = 'projects'
       AND column_name = 'size'
  ) THEN
    UPDATE projects p
       SET industry_size_id = CASE lower(btrim(p.size))
         WHEN 'has < 20 employees' THEN 1
         WHEN 'has 20-249 employees' THEN 2
         WHEN 'has 250+ employees' THEN 3
         ELSE p.industry_size_id
       END
     WHERE p.industry_size_id IS NULL
       AND p.size IS NOT NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
      FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = 'projects'
       AND column_name = 'type'
  ) THEN
    UPDATE projects p
       SET industry_type_id = CASE lower(btrim(p."type"))
         WHEN 'is not a government entity' THEN 1
         WHEN 'is not a goverment entity' THEN 1
         WHEN 'is a state government entity' THEN 2
         WHEN 'is a state goverment entity' THEN 2
         WHEN 'is a local government entity' THEN 3
         WHEN 'is a local goverment entity' THEN 3
         ELSE p.industry_type_id
       END
     WHERE p.industry_type_id IS NULL
       AND p."type" IS NOT NULL;
  END IF;
END $$;

ALTER TABLE projects
  DROP COLUMN IF EXISTS size;

ALTER TABLE projects
  DROP COLUMN IF EXISTS "type";

CREATE INDEX IF NOT EXISTS ix_projects_tenant_contractor_company_id
  ON projects(tenant_id, contractor_company_id);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_subcontractor_company_id
  ON projects(tenant_id, subcontractor_company_id);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_contact_id
  ON projects(tenant_id, contact_id);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_state_id
  ON projects(tenant_id, state_id);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_industry_size_id
  ON projects(tenant_id, industry_size_id);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_industry_type_id
  ON projects(tenant_id, industry_type_id);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_status
  ON projects(tenant_id, status);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_projects_contractor_company'
  ) THEN
    ALTER TABLE projects
      ADD CONSTRAINT fk_projects_contractor_company
      FOREIGN KEY (contractor_company_id) REFERENCES company(id) NOT VALID;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_projects_subcontractor_company'
  ) THEN
    ALTER TABLE projects
      ADD CONSTRAINT fk_projects_subcontractor_company
      FOREIGN KEY (subcontractor_company_id) REFERENCES company(id) NOT VALID;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_projects_contact_user'
  ) THEN
    ALTER TABLE projects
      ADD CONSTRAINT fk_projects_contact_user
      FOREIGN KEY (contact_id) REFERENCES users(id) NOT VALID;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_projects_industry_size'
  ) THEN
    ALTER TABLE projects
      ADD CONSTRAINT fk_projects_industry_size
      FOREIGN KEY (industry_size_id) REFERENCES industry_size(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_projects_industry_type'
  ) THEN
    ALTER TABLE projects
      ADD CONSTRAINT fk_projects_industry_type
      FOREIGN KEY (industry_type_id) REFERENCES industry_type(id);
  END IF;
END $$;

CREATE TEMP TABLE _ps_reference_model_seed (
  model_id   TEXT PRIMARY KEY,
  title      TEXT NOT NULL,
  table_name TEXT NOT NULL,
  data_view  TEXT NOT NULL,
  grid_view  TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO _ps_reference_model_seed (model_id, title, table_name, data_view, grid_view)
VALUES
  ('industry_size', 'Industry Size', 'industry_size', 'vw_industry_size', 'vg_industry_size__default'),
  ('industry_type', 'Industry Type', 'industry_type', 'vw_industry_type', 'vg_industry_type__default');

WITH field_payload AS (
  SELECT
    seed.model_id,
    jsonb_build_array(jsonb_build_object(
      'id', 'name',
      'fieldId', 'name',
      'family', 'core',
      'kind', 'short_text',
      'label', 'Name',
      'displayName', 'Name',
      'storageKey', 'name',
      'schemaScopeId', 'root',
      'schemaScopeKey', 'root',
      'status', 'persisted',
      'isPersisted', true,
      'runtime', jsonb_build_object(
        'sourceColumnName', 'name',
        'sourceValueKind', 'scalar'
      )
    )) AS fields_json,
    jsonb_build_array(jsonb_build_object(
      'containerKey', '__scope_root__',
      'fieldId', 'name',
      'order', 0
    )) AS placements_json
  FROM _ps_reference_model_seed seed
)
INSERT INTO ps_model (
  model_id,
  model_key,
  storage_key,
  display_name,
  description,
  source_type,
  status,
  version,
  published_version,
  structure_version,
  model_locked,
  definition_json
)
SELECT
  seed.model_id,
  seed.model_id,
  seed.table_name,
  seed.title,
  '',
  'external',
  'draft',
  1,
  0,
  1,
  true,
  jsonb_build_object(
    'id', seed.model_id,
    'key', seed.model_id,
    'name', seed.title,
    'title', seed.title,
    'displayName', seed.title,
    'description', '',
    'sourceType', 'external',
    'storageKey', seed.table_name,
    'version', 1,
    'publishedVersion', 0,
    'modelStructureVersion', 1,
    'modelLocked', true,
    'isStructureLocked', true,
    'canEditViewsOnly', true,
    'dataSchema', jsonb_build_object(
      'modelId', seed.model_id,
      'modelTitle', seed.title,
      'rootScope', jsonb_build_object(
        'schemaScopeId', 'root',
        'scopeType', 'ROOT',
        'fields', field_payload.fields_json,
        'runtime', jsonb_build_object(
          'rtAlias', seed.table_name,
          'tableName', seed.table_name,
          'mvTableName', '',
          'dataViewName', seed.data_view,
          'sourceIdColumn', 'id',
          'tenantScoped', false
        )
      ),
      'subformScopes', '[]'::jsonb
    ),
    'layoutBlueprint', jsonb_build_object(
      'rootScope', jsonb_build_object(
        'schemaScopeId', 'root',
        'containers', '[]'::jsonb,
        'fieldPlacements', field_payload.placements_json,
        'unplacedFieldIds', '[]'::jsonb
      ),
      'subformScopes', '[]'::jsonb
    )
  )
FROM _ps_reference_model_seed seed
JOIN field_payload ON field_payload.model_id = seed.model_id
ON CONFLICT (model_id) DO NOTHING;

INSERT INTO ps_view (
  model_id,
  view_id,
  view_key,
  display_name,
  description,
  view_type,
  is_default,
  is_active,
  view_locked,
  status,
  version,
  published_version,
  last_aligned_model_structure_version,
  definition_json,
  published_artifacts_json
)
SELECT
  seed.model_id,
  'view-default',
  'default',
  seed.title,
  '',
  'form',
  true,
  true,
  false,
  'draft',
  1,
  0,
  1,
  jsonb_build_object(
    'id', 'view-default',
    'key', 'default',
    'modelId', seed.model_id,
    'name', seed.title,
    'title', seed.title,
    'displayName', seed.title,
    'description', '',
    'kind', 'form',
    'isDefault', true,
    'isViewLocked', false,
    'viewLocked', false,
    'version', 1,
    'viewVersion', 1,
    'publishedVersion', 0,
    'lastAlignedModelStructureVersion', 1,
    'selectedScopeId', 'root',
    'uiSchema', jsonb_build_object(
      'currentParentId', NULL,
      'rootScope', jsonb_build_object(
        'schemaScopeId', 'root',
        'runtime', jsonb_build_object(
          'viewRtAlias', 'default',
          'dataViewName', seed.data_view,
          'gridViewName', seed.grid_view
        ),
        'nodes', jsonb_build_array(jsonb_build_object(
          'id', 'root-field-name',
          'type', 'field',
          'fieldId', 'name',
          'order', 0
        )),
        'selectedNodeId', NULL,
        'unplacedFieldIds', '[]'::jsonb,
        'filterDefinitions', jsonb_build_object(
          'defaultFilters', jsonb_build_object(
            'conditions', '[]'::jsonb,
            'logic', 'and'
          ),
          'quickFilters', '[]'::jsonb,
          'version', 1
        ),
        'viewSettings', jsonb_build_object(
          'actions', jsonb_build_object(
            'canAdd', true,
            'canDelete', true,
            'canEdit', true,
            'canView', true
          ),
          'list', jsonb_build_object(
            'columns', jsonb_build_array(jsonb_build_object(
              'id', 'grid-column-name',
              'fieldId', 'name',
              'order', 0,
              'visible', true
            )),
            'sorting', jsonb_build_object(
              'fieldId', 'name',
              'direction', 'asc'
            )
          )
        )
      ),
      'subformScopes', '[]'::jsonb
    )
  ),
  '{}'::jsonb
FROM _ps_reference_model_seed seed
ON CONFLICT (model_id, view_id) DO NOTHING;

CREATE TEMP TABLE _ps_projects_field_seed (
  field_id          TEXT PRIMARY KEY,
  label             TEXT NOT NULL,
  kind              TEXT NOT NULL,
  family            TEXT NOT NULL,
  source_column     TEXT,
  source_value_kind TEXT NOT NULL,
  preset            TEXT,
  lookup_model      TEXT,
  lookup_label      TEXT,
  display_fields    TEXT[],
  suggest_config    JSONB,
  options           TEXT[],
  choice_display    JSONB,
  order_index       INTEGER NOT NULL
) ON COMMIT DROP;

INSERT INTO _ps_projects_field_seed (
  field_id,
  label,
  kind,
  family,
  source_column,
  source_value_kind,
  preset,
  lookup_model,
  lookup_label,
  display_fields,
  suggest_config,
  options,
  choice_display,
  order_index
)
VALUES
  ('project_number', 'Project #', 'short_text', 'core', 'project_number', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
  ('name', 'Project Name', 'short_text', 'core', 'name', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1),
  ('year', 'Year', 'short_text', 'preset', 'year', 'scalar', 'suggest_text', NULL, NULL, NULL, '{"sourceMode":"same_field_distinct_values","searchMode":"contains","minQueryLength":1,"maxResults":20,"allowCustomValue":true}'::jsonb, NULL, NULL, 2),
  ('start_date', 'Start Date', 'date', 'core', 'start_date', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3),
  ('end_date', 'Completion Date', 'date', 'core', 'end_date', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4),
  ('contract_value', 'Project Value', 'currency', 'core', 'contract_value', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5),
  ('company', 'Business Unit', 'db_lookup', 'preset', 'company_id', 'lookup_id', 'company_lookup', 'company', 'Company', ARRAY['name'], NULL, NULL, NULL, 6),
  ('cm', 'CM', 'db_lookup', 'preset', 'contractor_company_id', 'lookup_id', 'company_lookup', 'company', 'Company', ARRAY['name'], NULL, NULL, NULL, 7),
  ('gc', 'GC', 'db_lookup', 'preset', 'subcontractor_company_id', 'lookup_id', 'company_lookup', 'company', 'Company', ARRAY['name'], NULL, NULL, NULL, 8),
  ('naics_code', 'NAICS Code', 'short_text', 'preset', 'naics_code', 'scalar', 'suggest_text', NULL, NULL, NULL, '{"sourceMode":"same_field_distinct_values","searchMode":"contains","minQueryLength":1,"maxResults":20,"allowCustomValue":true}'::jsonb, NULL, NULL, 9),
  ('industry_description', 'Industry Description', 'short_text', 'preset', 'industry_description', 'scalar', 'suggest_text', NULL, NULL, NULL, '{"sourceMode":"same_field_distinct_values","searchMode":"contains","minQueryLength":1,"maxResults":20,"allowCustomValue":true}'::jsonb, NULL, NULL, 10),
  ('avg', 'Annual Average Employee', 'short_text', 'preset', 'avg', 'scalar', 'suggest_text', NULL, NULL, NULL, '{"sourceMode":"same_field_distinct_values","searchMode":"contains","minQueryLength":1,"maxResults":20,"allowCustomValue":true}'::jsonb, NULL, NULL, 11),
  ('status', 'Status', 'single_select', 'choice', 'status', 'scalar', NULL, NULL, NULL, NULL, NULL, ARRAY['Active', 'Completed', '100%', 'Cancelled'], '{"allowEmpty":false,"orientation":"horizontal","renderStyle":"native"}'::jsonb, 12),
  ('active', 'Active', 'boolean', 'core', 'active', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13),
  ('industry_size', 'Industry Size', 'db_lookup', 'preset', 'industry_size_id', 'lookup_id', NULL, 'industry_size', 'Industry Size', ARRAY['name'], NULL, NULL, NULL, 14),
  ('industry_type', 'Industry Type', 'db_lookup', 'preset', 'industry_type_id', 'lookup_id', NULL, 'industry_type', 'Industry Type', ARRAY['name'], NULL, NULL, NULL, 15),
  ('address_line_1', 'Address', 'long_text', 'core', 'address_line_1', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16),
  ('address_line_2', 'Address2', 'long_text', 'core', 'address_line_2', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17),
  ('phone', 'Phone', 'short_text', 'preset', 'phone', 'scalar', 'phone', NULL, NULL, NULL, NULL, NULL, NULL, 18),
  ('fax', 'Fax', 'short_text', 'core', 'fax', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19),
  ('email', 'Email', 'short_text', 'preset', 'email', 'scalar', 'email', NULL, NULL, NULL, NULL, NULL, NULL, 20),
  ('city', 'City', 'short_text', 'preset', 'city', 'scalar', 'suggest_text', NULL, NULL, NULL, '{"sourceMode":"same_field_distinct_values","searchMode":"contains","minQueryLength":1,"maxResults":20,"allowCustomValue":true}'::jsonb, NULL, NULL, 21),
  ('zip', 'Zip', 'short_text', 'preset', 'zip', 'scalar', 'suggest_text', NULL, NULL, NULL, '{"sourceMode":"same_field_distinct_values","searchMode":"contains","minQueryLength":1,"maxResults":20,"allowCustomValue":true}'::jsonb, NULL, NULL, 22),
  ('state', 'State', 'db_lookup', 'preset', 'state_id', 'lookup_id', NULL, 'state', 'State', ARRAY['name'], NULL, NULL, NULL, 23),
  ('contact', 'Contact', 'db_lookup', 'preset', 'contact_id', 'lookup_id', 'contact_lookup', 'users', 'Contact', ARRAY['first_name', 'last_name'], NULL, NULL, NULL, 24),
  ('geo_code', 'GEO Code', 'short_text', 'core', 'geo_code', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25),
  ('description', 'Description', 'long_text', 'core', 'description', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 26),
  ('info', 'Info', 'long_text', 'core', 'info', 'scalar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 27);

CREATE TEMP TABLE _ps_projects_layout_container_seed (
  container_key        TEXT PRIMARY KEY,
  type                 TEXT NOT NULL,
  title                TEXT,
  parent_container_key TEXT NOT NULL,
  order_index          INTEGER NOT NULL
) ON COMMIT DROP;

INSERT INTO _ps_projects_layout_container_seed (
  container_key,
  type,
  title,
  parent_container_key,
  order_index
)
VALUES
  ('root.tabs.projects', 'tabs', NULL, '', 0),
  ('root.tabs.projects.main', 'tab_item', 'Main', 'root.tabs.projects', 0),
  ('root.tabs.projects.details', 'tab_item', 'Details', 'root.tabs.projects', 1);

CREATE TEMP TABLE _ps_projects_field_placement_seed (
  field_id      TEXT PRIMARY KEY,
  container_key TEXT NOT NULL,
  order_index   INTEGER NOT NULL
) ON COMMIT DROP;

INSERT INTO _ps_projects_field_placement_seed (field_id, container_key, order_index)
VALUES
  ('project_number', 'root.tabs.projects.main', 0),
  ('name', 'root.tabs.projects.main', 1),
  ('year', 'root.tabs.projects.main', 2),
  ('start_date', 'root.tabs.projects.main', 3),
  ('end_date', 'root.tabs.projects.main', 4),
  ('contract_value', 'root.tabs.projects.main', 5),
  ('company', 'root.tabs.projects.main', 6),
  ('cm', 'root.tabs.projects.main', 7),
  ('gc', 'root.tabs.projects.main', 8),
  ('naics_code', 'root.tabs.projects.main', 9),
  ('industry_description', 'root.tabs.projects.main', 10),
  ('avg', 'root.tabs.projects.main', 11),
  ('status', 'root.tabs.projects.main', 12),
  ('active', 'root.tabs.projects.main', 13),
  ('industry_size', 'root.tabs.projects.main', 14),
  ('industry_type', 'root.tabs.projects.main', 15),
  ('address_line_1', 'root.tabs.projects.details', 0),
  ('address_line_2', 'root.tabs.projects.details', 1),
  ('phone', 'root.tabs.projects.details', 2),
  ('fax', 'root.tabs.projects.details', 3),
  ('email', 'root.tabs.projects.details', 4),
  ('city', 'root.tabs.projects.details', 5),
  ('zip', 'root.tabs.projects.details', 6),
  ('state', 'root.tabs.projects.details', 7),
  ('contact', 'root.tabs.projects.details', 8),
  ('geo_code', 'root.tabs.projects.details', 9),
  ('description', 'root.tabs.projects.details', 10),
  ('info', 'root.tabs.projects.details', 11);

CREATE TEMP TABLE _ps_projects_view_node_seed (
  node_id     TEXT PRIMARY KEY,
  node_type   TEXT NOT NULL,
  field_id    TEXT,
  title       TEXT,
  parent_id   TEXT,
  order_index INTEGER NOT NULL
) ON COMMIT DROP;

INSERT INTO _ps_projects_view_node_seed (node_id, node_type, field_id, title, parent_id, order_index)
VALUES
  ('root-tabs-projects', 'tabs', NULL, NULL, NULL, 0),
  ('root-tab-main', 'tab_item', NULL, 'Main', 'root-tabs-projects', 0),
  ('root-tab-details', 'tab_item', NULL, 'Details', 'root-tabs-projects', 1);

INSERT INTO _ps_projects_view_node_seed (node_id, node_type, field_id, title, parent_id, order_index)
SELECT
  'root-field-' || placement.field_id,
  'field',
  placement.field_id,
  NULL,
  CASE placement.container_key
    WHEN 'root.tabs.projects.main' THEN 'root-tab-main'
    ELSE 'root-tab-details'
  END,
  placement.order_index
FROM _ps_projects_field_placement_seed placement;

CREATE TEMP TABLE _ps_projects_grid_column_seed (
  field_id    TEXT PRIMARY KEY,
  order_index INTEGER NOT NULL
) ON COMMIT DROP;

INSERT INTO _ps_projects_grid_column_seed (field_id, order_index)
VALUES
  ('project_number', 0),
  ('name', 1),
  ('company', 2),
  ('cm', 3),
  ('gc', 4),
  ('status', 5),
  ('active', 6);

WITH field_payload AS (
  SELECT jsonb_agg(
           jsonb_strip_nulls(
             jsonb_build_object(
               'id', field_id,
               'fieldId', field_id,
               'family', family,
               'kind', kind,
               'label', label,
               'displayName', label,
               'storageKey', field_id,
               'schemaScopeId', 'root',
               'schemaScopeKey', 'root',
               'status', 'persisted',
               'isPersisted', true,
               'runtime', jsonb_strip_nulls(jsonb_build_object(
                 'sourceColumnName', source_column,
                 'sourceValueKind', source_value_kind
               ))
             )
           )
           || CASE
             WHEN preset IS NOT NULL THEN jsonb_build_object('preset', preset)
             ELSE '{}'::jsonb
           END
           || CASE
             WHEN lookup_model IS NOT NULL THEN jsonb_build_object(
               'lookupConfig', jsonb_build_object('sourceModel', lookup_model),
               'selectionMode', 'single',
               'sourceLabel', lookup_label,
               'displayFields', to_jsonb(display_fields)
             )
             ELSE '{}'::jsonb
           END
           || CASE
             WHEN suggest_config IS NOT NULL THEN jsonb_build_object('suggestConfig', suggest_config)
             ELSE '{}'::jsonb
           END
           || CASE
             WHEN options IS NOT NULL THEN jsonb_build_object('options', to_jsonb(options))
             ELSE '{}'::jsonb
           END
           || CASE
             WHEN choice_display IS NOT NULL THEN jsonb_build_object('choiceDisplay', choice_display)
             ELSE '{}'::jsonb
           END
           ORDER BY order_index
         ) AS fields_json
    FROM _ps_projects_field_seed
),
layout_payload AS (
  SELECT
    (
      SELECT jsonb_agg(
               jsonb_build_object(
                 'containerKey', container_key,
                 'type', type,
                 'title', title,
                 'parentContainerKey', parent_container_key,
                 'order', order_index
               )
               ORDER BY
                 CASE WHEN parent_container_key = '' THEN 0 ELSE 1 END,
                 parent_container_key,
                 order_index
             )
        FROM _ps_projects_layout_container_seed
    ) AS containers_json,
    (
      SELECT jsonb_agg(
               jsonb_build_object(
                 'containerKey', container_key,
                 'fieldId', field_id,
                 'order', order_index
               )
               ORDER BY container_key, order_index
             )
        FROM _ps_projects_field_placement_seed
    ) AS placements_json
)
INSERT INTO ps_model (
  model_id,
  model_key,
  storage_key,
  display_name,
  description,
  source_type,
  status,
  version,
  published_version,
  structure_version,
  model_locked,
  definition_json
)
SELECT
  'projects',
  'projects',
  'projects',
  'Projects',
  '',
  'external',
  'draft',
  1,
  0,
  1,
  true,
  jsonb_build_object(
    'id', 'projects',
    'key', 'projects',
    'name', 'Projects',
    'title', 'Projects',
    'displayName', 'Projects',
    'description', '',
    'sourceType', 'external',
    'storageKey', 'projects',
    'version', 1,
    'publishedVersion', 0,
    'modelStructureVersion', 1,
    'modelLocked', true,
    'isStructureLocked', true,
    'canEditViewsOnly', true,
    'dataSchema', jsonb_build_object(
      'modelId', 'projects',
      'modelTitle', 'Projects',
      'rootScope', jsonb_build_object(
        'schemaScopeId', 'root',
        'scopeType', 'ROOT',
        'fields', field_payload.fields_json,
        'runtime', jsonb_build_object(
          'rtAlias', 'projects',
          'tableName', 'projects',
          'mvTableName', '',
          'dataViewName', 'vw_projects',
          'sourceIdColumn', 'id',
          'sourceTenantIdColumn', 'tenant_id',
          'sourceGuidColumn', 'guid',
          'sourceCreatedAtColumn', 'created_at',
          'sourceUpdatedAtColumn', 'updated_at',
          'tenantScoped', true
        )
      ),
      'subformScopes', '[]'::jsonb
    ),
    'layoutBlueprint', jsonb_build_object(
      'rootScope', jsonb_build_object(
        'schemaScopeId', 'root',
        'containers', layout_payload.containers_json,
        'fieldPlacements', layout_payload.placements_json,
        'unplacedFieldIds', '[]'::jsonb
      ),
      'subformScopes', '[]'::jsonb
    )
  )
FROM field_payload, layout_payload
ON CONFLICT (model_id) DO NOTHING;

WITH nodes_payload AS (
  SELECT jsonb_agg(
           jsonb_strip_nulls(jsonb_build_object(
             'id', node_id,
             'type', node_type,
             'fieldId', field_id,
             'title', title,
             'parentId', parent_id,
             'order', order_index
           ))
           ORDER BY
             CASE
               WHEN node_id = 'root-tabs-projects' THEN 0
               WHEN node_id = 'root-tab-main' THEN 1
               WHEN parent_id = 'root-tab-main' THEN 2
               WHEN node_id = 'root-tab-details' THEN 3
               ELSE 4
             END,
             parent_id,
             order_index
         ) AS nodes_json
    FROM _ps_projects_view_node_seed
),
columns_payload AS (
  SELECT jsonb_agg(
           jsonb_build_object(
             'id', 'grid-column-' || field_id,
             'fieldId', field_id,
             'order', order_index,
             'visible', true
           )
           ORDER BY order_index
         ) AS columns_json
    FROM _ps_projects_grid_column_seed
)
INSERT INTO ps_view (
  model_id,
  view_id,
  view_key,
  display_name,
  description,
  view_type,
  is_default,
  is_active,
  view_locked,
  status,
  version,
  published_version,
  last_aligned_model_structure_version,
  definition_json,
  published_artifacts_json
)
SELECT
  'projects',
  'view-default',
  'default',
  'Projects',
  '',
  'form',
  true,
  true,
  false,
  'draft',
  1,
  0,
  1,
  jsonb_build_object(
    'id', 'view-default',
    'key', 'default',
    'modelId', 'projects',
    'name', 'Projects',
    'title', 'Projects',
    'displayName', 'Projects',
    'description', '',
    'kind', 'form',
    'isDefault', true,
    'isViewLocked', false,
    'viewLocked', false,
    'version', 1,
    'viewVersion', 1,
    'publishedVersion', 0,
    'lastAlignedModelStructureVersion', 1,
    'selectedScopeId', 'root',
    'uiSchema', jsonb_build_object(
      'currentParentId', NULL,
      'rootScope', jsonb_build_object(
        'schemaScopeId', 'root',
        'runtime', jsonb_build_object(
          'viewRtAlias', 'default',
          'dataViewName', 'vw_projects',
          'gridViewName', 'vg_projects__default'
        ),
        'nodes', nodes_payload.nodes_json,
        'selectedNodeId', NULL,
        'unplacedFieldIds', '[]'::jsonb,
        'filterDefinitions', jsonb_build_object(
          'defaultFilters', jsonb_build_object(
            'conditions', '[]'::jsonb,
            'logic', 'and'
          ),
          'quickFilters', '[]'::jsonb,
          'version', 1
        ),
        'viewSettings', jsonb_build_object(
          'actions', jsonb_build_object(
            'canAdd', true,
            'canDelete', true,
            'canEdit', true,
            'canView', true
          ),
          'list', jsonb_build_object(
            'columns', columns_payload.columns_json,
            'sorting', jsonb_build_object(
              'fieldId', 'project_number',
              'direction', 'asc'
            )
          )
        )
      ),
      'subformScopes', '[]'::jsonb
    )
  ),
  '{}'::jsonb
FROM nodes_payload, columns_payload
ON CONFLICT (model_id, view_id) DO NOTHING;

CREATE OR REPLACE VIEW public.vw_industry_size AS
SELECT
  t.id AS _id,
  NULL::bigint AS tenant_id,
  NULL::uuid AS _guid,
  NULL::timestamptz AS _created_at,
  NULL::timestamptz AS _updated_at,
  t.name AS name
FROM public.industry_size t;

CREATE OR REPLACE VIEW public.vg_industry_size__default AS
SELECT
  _id,
  tenant_id,
  _guid,
  _created_at,
  _updated_at,
  name
FROM public.vw_industry_size;

CREATE OR REPLACE VIEW public.vw_industry_type AS
SELECT
  t.id AS _id,
  NULL::bigint AS tenant_id,
  NULL::uuid AS _guid,
  NULL::timestamptz AS _created_at,
  NULL::timestamptz AS _updated_at,
  t.name AS name
FROM public.industry_type t;

CREATE OR REPLACE VIEW public.vg_industry_type__default AS
SELECT
  _id,
  tenant_id,
  _guid,
  _created_at,
  _updated_at,
  name
FROM public.vw_industry_type;

CREATE OR REPLACE VIEW public.vw_projects AS
SELECT
  t.id AS _id,
  t.tenant_id AS tenant_id,
  t.guid AS _guid,
  t.created_at AS _created_at,
  t.updated_at AS _updated_at,
  t.project_number AS project_number,
  t.name AS name,
  t.year AS year,
  t.start_date AS start_date,
  t.end_date AS end_date,
  t.contract_value AS contract_value,
  t.company_id AS company_id,
  NULLIF(lk_company.name::text, '') AS company__label,
  NULLIF(lk_company_type.name::text, '') AS company__type,
  NULLIF(lk_company_main.name::text, '') AS company__main_company_name,
  NULLIF(lk_company_state.name::text, '') AS company__state,
  t.contractor_company_id AS contractor_company_id,
  NULLIF(lk_cm.name::text, '') AS cm__label,
  NULLIF(lk_cm_type.name::text, '') AS cm__type,
  NULLIF(lk_cm_main.name::text, '') AS cm__main_company_name,
  NULLIF(lk_cm_state.name::text, '') AS cm__state,
  t.subcontractor_company_id AS subcontractor_company_id,
  NULLIF(lk_gc.name::text, '') AS gc__label,
  NULLIF(lk_gc_type.name::text, '') AS gc__type,
  NULLIF(lk_gc_main.name::text, '') AS gc__main_company_name,
  NULLIF(lk_gc_state.name::text, '') AS gc__state,
  t.naics_code AS naics_code,
  t.industry_description AS industry_description,
  t.avg AS avg,
  t.status AS status,
  t.active AS active,
  t.industry_size_id AS industry_size_id,
  NULLIF(lk_industry_size.name::text, '') AS industry_size__label,
  t.industry_type_id AS industry_type_id,
  NULLIF(lk_industry_type.name::text, '') AS industry_type__label,
  t.address_line_1 AS address_line_1,
  t.address_line_2 AS address_line_2,
  t.phone AS phone,
  t.fax AS fax,
  t.email::text AS email,
  t.city AS city,
  t.zip AS zip,
  t.state_id AS state_id,
  NULLIF(lk_state.name::text, '') AS state__label,
  t.contact_id AS contact_id,
  NULLIF(concat_ws(' ', NULLIF(lk_contact.first_name, ''), NULLIF(lk_contact.last_name, '')), '') AS contact__label,
  NULLIF(lk_contact_company.name::text, '') AS contact__company_name,
  lk_contact.company_id AS contact__company_id,
  NULLIF(lk_contact_job_type.name::text, '') AS contact__title,
  NULLIF(COALESCE(lk_contact.mobile_phone, lk_contact.phone), '') AS contact__phone,
  t.geo_code AS geo_code,
  t.description AS description,
  t.info AS info
FROM public.projects t
LEFT JOIN public.company lk_company
  ON t.company_id = lk_company.id
 AND t.tenant_id = lk_company.tenant_id
LEFT JOIN public.companytype lk_company_type
  ON lk_company.company_type_id = lk_company_type.id
 AND lk_company.tenant_id = lk_company_type.tenant_id
LEFT JOIN public.company lk_company_main
  ON lk_company.main_company_id = lk_company_main.id
 AND lk_company.tenant_id = lk_company_main.tenant_id
LEFT JOIN public.state lk_company_state
  ON lk_company.state_id = lk_company_state.id
LEFT JOIN public.company lk_cm
  ON t.contractor_company_id = lk_cm.id
 AND t.tenant_id = lk_cm.tenant_id
LEFT JOIN public.companytype lk_cm_type
  ON lk_cm.company_type_id = lk_cm_type.id
 AND lk_cm.tenant_id = lk_cm_type.tenant_id
LEFT JOIN public.company lk_cm_main
  ON lk_cm.main_company_id = lk_cm_main.id
 AND lk_cm.tenant_id = lk_cm_main.tenant_id
LEFT JOIN public.state lk_cm_state
  ON lk_cm.state_id = lk_cm_state.id
LEFT JOIN public.company lk_gc
  ON t.subcontractor_company_id = lk_gc.id
 AND t.tenant_id = lk_gc.tenant_id
LEFT JOIN public.companytype lk_gc_type
  ON lk_gc.company_type_id = lk_gc_type.id
 AND lk_gc.tenant_id = lk_gc_type.tenant_id
LEFT JOIN public.company lk_gc_main
  ON lk_gc.main_company_id = lk_gc_main.id
 AND lk_gc.tenant_id = lk_gc_main.tenant_id
LEFT JOIN public.state lk_gc_state
  ON lk_gc.state_id = lk_gc_state.id
LEFT JOIN public.industry_size lk_industry_size
  ON t.industry_size_id = lk_industry_size.id
LEFT JOIN public.industry_type lk_industry_type
  ON t.industry_type_id = lk_industry_type.id
LEFT JOIN public.state lk_state
  ON t.state_id = lk_state.id
LEFT JOIN public.users lk_contact
  ON t.contact_id = lk_contact.id
 AND t.tenant_id = lk_contact.tenant_id
LEFT JOIN public.company lk_contact_company
  ON lk_contact.company_id = lk_contact_company.id
 AND lk_contact.tenant_id = lk_contact_company.tenant_id
LEFT JOIN public.jobtype lk_contact_job_type
  ON lk_contact.job_type_id = lk_contact_job_type.id
 AND lk_contact.tenant_id = lk_contact_job_type.tenant_id;

CREATE OR REPLACE VIEW public.vg_projects__default AS
SELECT
  _id,
  tenant_id,
  _guid,
  _created_at,
  _updated_at,
  project_number,
  name,
  company__label AS company,
  cm__label AS cm,
  gc__label AS gc,
  status,
  active
FROM public.vw_projects;

COMMIT;
