BEGIN;

CREATE TABLE IF NOT EXISTS ps_navigation_runtime_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key TEXT NOT NULL DEFAULT 'default',
  owner_type TEXT NOT NULL,
  item_id TEXT NOT NULL,
  parent_item_id TEXT,
  node_type TEXT NOT NULL,
  target_type TEXT,
  target_model_id TEXT,
  target_view_id TEXT,
  target_page_id TEXT,
  target_module_id TEXT,
  target_route TEXT,
  target_path TEXT,
  external_url TEXT,
  label TEXT NOT NULL,
  icon TEXT,
  channel TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  depth INTEGER NOT NULL DEFAULT 0,
  breadcrumb_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ps_navigation_runtime_item_config_fk
    FOREIGN KEY (config_key) REFERENCES ps_navigation_config(config_key) ON DELETE CASCADE,
  CONSTRAINT ps_navigation_runtime_item_config_owner_item_key
    UNIQUE (config_key, owner_type, item_id),
  CONSTRAINT ps_navigation_runtime_item_config_key_chk CHECK (btrim(config_key) <> ''),
  CONSTRAINT ps_navigation_runtime_item_owner_type_chk
    CHECK (owner_type IN ('app_menu_item', 'utility_rail_item')),
  CONSTRAINT ps_navigation_runtime_item_item_id_chk CHECK (btrim(item_id) <> ''),
  CONSTRAINT ps_navigation_runtime_item_node_type_chk CHECK (btrim(node_type) <> ''),
  CONSTRAINT ps_navigation_runtime_item_label_chk CHECK (btrim(label) <> ''),
  CONSTRAINT ps_navigation_runtime_item_breadcrumb_chk CHECK (jsonb_typeof(breadcrumb_json) = 'array')
);

CREATE INDEX IF NOT EXISTS ix_ps_navigation_runtime_item_config_parent
  ON ps_navigation_runtime_item(config_key, owner_type, parent_item_id, sort_order);

CREATE INDEX IF NOT EXISTS ix_ps_navigation_runtime_item_target
  ON ps_navigation_runtime_item(config_key, target_type, target_model_id, target_view_id, target_page_id, target_module_id);

CREATE TABLE IF NOT EXISTS ps_navigation_access_policy (
  config_key TEXT NOT NULL DEFAULT 'default',
  owner_type TEXT NOT NULL,
  owner_id TEXT NOT NULL,
  access_mode TEXT NOT NULL DEFAULT 'inherit',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (config_key, owner_type, owner_id),
  CONSTRAINT ps_navigation_access_policy_item_fk
    FOREIGN KEY (config_key, owner_type, owner_id)
    REFERENCES ps_navigation_runtime_item(config_key, owner_type, item_id)
    ON DELETE CASCADE,
  CONSTRAINT ps_navigation_access_policy_owner_type_chk
    CHECK (owner_type IN ('app_menu_item', 'utility_rail_item')),
  CONSTRAINT ps_navigation_access_policy_owner_id_chk CHECK (btrim(owner_id) <> ''),
  CONSTRAINT ps_navigation_access_policy_mode_chk
    CHECK (access_mode IN ('inherit', 'all_authenticated', 'selected_only', 'everyone_except'))
);

CREATE INDEX IF NOT EXISTS ix_ps_navigation_access_policy_config_mode
  ON ps_navigation_access_policy(config_key, access_mode);

CREATE TABLE IF NOT EXISTS ps_navigation_access_subject (
  config_key TEXT NOT NULL DEFAULT 'default',
  owner_type TEXT NOT NULL,
  owner_id TEXT NOT NULL,
  subject_type TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (config_key, owner_type, owner_id, subject_type, subject_id),
  CONSTRAINT ps_navigation_access_subject_policy_fk
    FOREIGN KEY (config_key, owner_type, owner_id)
    REFERENCES ps_navigation_access_policy(config_key, owner_type, owner_id)
    ON DELETE CASCADE,
  CONSTRAINT ps_navigation_access_subject_owner_type_chk
    CHECK (owner_type IN ('app_menu_item', 'utility_rail_item')),
  CONSTRAINT ps_navigation_access_subject_subject_type_chk
    CHECK (subject_type IN ('user', 'company', 'jobtype')),
  CONSTRAINT ps_navigation_access_subject_subject_id_chk CHECK (btrim(subject_id) <> '')
);

CREATE INDEX IF NOT EXISTS ix_ps_navigation_access_subject_lookup
  ON ps_navigation_access_subject(config_key, subject_type, subject_id);

COMMIT;
