CREATE TABLE IF NOT EXISTS ps_model (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid               UUID NOT NULL DEFAULT gen_random_uuid(),
  model_id           TEXT NOT NULL,
  model_key          TEXT NOT NULL,
  storage_key        TEXT,
  display_name       TEXT NOT NULL,
  description        TEXT,
  source_type        TEXT NOT NULL DEFAULT 'managed',
  status             TEXT NOT NULL DEFAULT 'draft',
  version            BIGINT NOT NULL DEFAULT 1,
  published_version  BIGINT NOT NULL DEFAULT 0,
  structure_version  BIGINT NOT NULL DEFAULT 1,
  definition_json    JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ps_model_model_id
  ON ps_model(model_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ps_model_guid
  ON ps_model(guid);

CREATE INDEX IF NOT EXISTS ix_ps_model_updated_at
  ON ps_model(updated_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_ps_model_updated_at') THEN
    CREATE TRIGGER trg_ps_model_updated_at
      BEFORE UPDATE ON ps_model
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS ps_view (
  id                                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid                                   UUID NOT NULL DEFAULT gen_random_uuid(),
  model_id                               TEXT NOT NULL REFERENCES ps_model(model_id) ON DELETE CASCADE,
  view_id                                TEXT NOT NULL,
  view_key                               TEXT NOT NULL,
  display_name                           TEXT NOT NULL,
  description                            TEXT,
  view_type                              TEXT NOT NULL DEFAULT 'form',
  is_default                             BOOLEAN NOT NULL DEFAULT false,
  status                                 TEXT NOT NULL DEFAULT 'draft',
  version                                BIGINT NOT NULL DEFAULT 1,
  published_version                      BIGINT NOT NULL DEFAULT 0,
  last_aligned_model_structure_version   BIGINT NOT NULL DEFAULT 1,
  definition_json                        JSONB NOT NULL DEFAULT '{}'::jsonb,
  published_artifacts_json               JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at                             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ps_view_model_view_id
  ON ps_view(model_id, view_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ps_view_guid
  ON ps_view(guid);

CREATE INDEX IF NOT EXISTS ix_ps_view_model_id
  ON ps_view(model_id);

CREATE INDEX IF NOT EXISTS ix_ps_view_updated_at
  ON ps_view(updated_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_ps_view_updated_at') THEN
    CREATE TRIGGER trg_ps_view_updated_at
      BEFORE UPDATE ON ps_view
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;
