CREATE TABLE IF NOT EXISTS events (
  events_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  events_tenant_id   BIGINT,
  events_date        DATE,
  events_event       TEXT NOT NULL,
  events_module      TEXT,
  events_record      BIGINT,
  events_table       TEXT,
  events_text        TEXT,
  events_time        TIMESTAMPTZ,
  events_timezone    TEXT,
  events_users_id    BIGINT,
  events_actor_guid  UUID,
  events_users_ip    INET,
  events_to          TEXT,
  events_subject     TEXT,
  events_body        TEXT,
  events_data        JSONB NOT NULL DEFAULT '{}'::jsonb,
  events_files       JSONB,
  events_urls        JSONB,
  events_created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  events_updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (events_created_at, events_id)
) PARTITION BY RANGE (events_created_at);

CREATE TABLE IF NOT EXISTS events_default PARTITION OF events DEFAULT;

DO $$
DECLARE
  quarter_base DATE := date_trunc('quarter', current_date)::date;
  part_start   DATE;
  part_end     DATE;
  part_name    TEXT;
BEGIN
  FOR i IN -1..8 LOOP
    part_start := (quarter_base + make_interval(months => i * 3))::date;
    part_end := (part_start + INTERVAL '3 months')::date;
    part_name := format('events_y%s_q%s',
      EXTRACT(YEAR FROM part_start)::int,
      EXTRACT(QUARTER FROM part_start)::int
    );

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I PARTITION OF events FOR VALUES FROM (%L) TO (%L)',
      part_name,
      part_start,
      part_end
    );
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS ix_events_tenant_created
  ON events(events_tenant_id, events_created_at DESC);
CREATE INDEX IF NOT EXISTS ix_events_tenant_event_created
  ON events(events_tenant_id, events_event, events_created_at DESC);
CREATE INDEX IF NOT EXISTS ix_events_actor_created
  ON events(events_actor_guid, events_created_at DESC)
  WHERE events_actor_guid IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_events_module_created
  ON events(events_module, events_created_at DESC);
