CREATE TABLE IF NOT EXISTS events (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
  guid           UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id      BIGINT,
  user_id        BIGINT,
  principal_guid UUID,
  occurred_at    TIMESTAMPTZ,
  event          TEXT NOT NULL,
  module         TEXT,
  record_id      BIGINT,
  table_name     TEXT,
  text           TEXT,
  timezone_name  TEXT,
  user_ip        TEXT,
  recipients     TEXT,
  subject        TEXT,
  body           TEXT,
  data           JSONB NOT NULL DEFAULT '{}'::jsonb,
  files          JSONB,
  urls           JSONB,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (created_at, id)
) PARTITION BY RANGE (created_at);

CREATE TABLE IF NOT EXISTS events_default PARTITION OF events DEFAULT;

DO $$
DECLARE
  quarter_base DATE := date_trunc('quarter', current_date)::date;
  part_start   DATE;
  part_end     DATE;
  part_name    TEXT;
BEGIN
  FOR i IN -1..8 LOOP
    part_start := (quarter_base + make_interval(months => i * 3))::date;
    part_end := (part_start + INTERVAL '3 months')::date;
    part_name := format('events_y%s_q%s',
      EXTRACT(YEAR FROM part_start)::int,
      EXTRACT(QUARTER FROM part_start)::int
    );

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I PARTITION OF events FOR VALUES FROM (%L) TO (%L)',
      part_name,
      part_start,
      part_end
    );
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS ix_events_tenant_created
  ON events(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_events_guid_created
  ON events(guid, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_events_tenant_event_created
  ON events(tenant_id, event, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_events_principal_created
  ON events(principal_guid, created_at DESC)
  WHERE principal_guid IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_events_module_created
  ON events(module, created_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_events_updated_at') THEN
    CREATE TRIGGER trg_events_updated_at
      BEFORE UPDATE ON events
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;
