CREATE TABLE IF NOT EXISTS mails (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid             UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id        BIGINT,
  user_id          BIGINT,
  sent_at          TIMESTAMPTZ,
  timezone_name    TEXT,
  from_address     TEXT,
  to_addresses     TEXT,
  cc_addresses     TEXT,
  bcc_addresses    TEXT,
  subject          TEXT,
  body             TEXT,
  sender_name      TEXT,
  files            JSONB,
  urls             JSONB,
  target_table     TEXT,
  target_record_id BIGINT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_mails_tenant_user
  ON mails(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS ix_mails_tenant_target_record_id
  ON mails(tenant_id, target_record_id);
CREATE INDEX IF NOT EXISTS ix_mails_tenant_sent_at
  ON mails(tenant_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS ix_mails_guid_created
  ON mails(guid, created_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_mails_updated_at') THEN
    CREATE TRIGGER trg_mails_updated_at
      BEFORE UPDATE ON mails
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;
