<!-- Generated by `node .agent-cli/bin/agent-stack.mjs render-runtimes`. Edit `.agent-code/` and rerender. -->

# Cursor rule: routing

- Use the `maestro` skill for inline request clarification, module artifacts, feature seeding, launch readiness, and research review gates.
- Use the `charlie` skill for grounded codebase research.
- When native delegation is needed, the canonical system agent names are:
  - `module_orchestrator`
  - `research_codebase`
- This stack intentionally has no `.cursor/commands/` layer.
