package platformstudioformbuilder

import (
	"context"
	"crypto/sha1"
	"database/sql"
	"encoding/hex"
	"fmt"
	"strings"

	"dtriton.com/platform/backend/internal/platform/httpx/requestctx"
)

func (r *repository) ApplyRuntime(ctx context.Context, tenant requestctx.TenantInfo, plan runtimeApplyPlan) (*RuntimeApplySummary, error) {
	if plan.ModelSourceType != "" && plan.ModelSourceType != "managed" {
		return &RuntimeApplySummary{
			Status:  "skipped",
			Message: "runtime apply currently supports managed models only",
		}, nil
	}

	db, err := r.client.OpenDBTenant(ctx, tenant.DBName, tenant.DBInstanceCode)
	if err != nil {
		return nil, fmt.Errorf("form builder: open tenant db for runtime apply: %w", err)
	}

	tx, err := db.BeginTx(ctx, &sql.TxOptions{})
	if err != nil {
		return nil, fmt.Errorf("form builder: begin runtime apply tx: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	summary := &RuntimeApplySummary{
		Status: "applied",
		StorageResults: &RuntimeApplyStorageResults{
			SubformScopes: []RuntimeApplyScopeResult{},
		},
	}

	rootScopeResult, err := applyRuntimeScopeTx(ctx, tx, plan.RootScope)
	if err != nil {
		return nil, err
	}
	summary.StorageResults.RootScope = rootScopeResult

	for _, scope := range plan.SubformScopes {
		scopeResult, err := applyRuntimeScopeTx(ctx, tx, scope)
		if err != nil {
			return nil, err
		}
		summary.StorageResults.SubformScopes = append(summary.StorageResults.SubformScopes, scopeResult)
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("form builder: commit runtime apply tx: %w", err)
	}

	return summary, nil
}

func applyRuntimeScopeTx(ctx context.Context, tx *sql.Tx, scope runtimeApplyScopePlan) (RuntimeApplyScopeResult, error) {
	result := RuntimeApplyScopeResult{
		ScopeID:       scope.ScopeID,
		GridViews:     []RuntimeApplyArtifactResult{},
		LookupOutputs: []RuntimeApplyLookupOutputResult{},
		Warnings:      []ValidationMessage{},
	}

	tableExisted, err := relationExistsTx(ctx, tx, scope.TableName)
	if err != nil {
		return result, err
	}
	if err := ensureManagedTableTx(ctx, tx, scope); err != nil {
		return result, err
	}
	result.Table = &RuntimeApplyArtifactResult{
		Name:   scope.TableName,
		Action: chooseRuntimeRelationAction(tableExisted),
	}

	multiValueFields := filterRuntimeMultiValueFields(scope.Fields)
	if len(multiValueFields) > 0 {
		mvExisted, err := relationExistsTx(ctx, tx, scope.MultiValueTableName)
		if err != nil {
			return result, err
		}
		if err := ensureManagedMultiValueTableTx(ctx, tx, scope); err != nil {
			return result, err
		}
		result.MultiValueTable = &RuntimeApplyArtifactResult{
			Name:   scope.MultiValueTableName,
			Action: chooseRuntimeRelationAction(mvExisted),
		}
	}

	dataViewExisted, err := relationExistsTx(ctx, tx, scope.DataViewName)
	if err != nil {
		return result, err
	}
	lookupOutputs, err := ensureScopeDataViewTx(ctx, tx, scope)
	if err != nil {
		return result, err
	}
	lookupOutputAction := chooseRuntimeViewAction(dataViewExisted)
	for index := range lookupOutputs {
		lookupOutputs[index].Action = lookupOutputAction
	}
	result.DataView = &RuntimeApplyArtifactResult{
		Name:   scope.DataViewName,
		Action: lookupOutputAction,
	}
	result.LookupOutputs = lookupOutputs

	for _, gridView := range scope.GridViews {
		gridExisted, err := relationExistsTx(ctx, tx, gridView.Name)
		if err != nil {
			return result, err
		}
		if err := ensureGridViewTx(ctx, tx, scope.DataViewName, gridView); err != nil {
			return result, err
		}
		result.GridViews = append(result.GridViews, RuntimeApplyArtifactResult{
			Name:   gridView.Name,
			Action: chooseRuntimeViewAction(gridExisted),
		})
	}

	for _, field := range scope.Fields {
		if field.WarningMessage == "" {
			continue
		}
		result.Warnings = append(result.Warnings, ValidationMessage{
			Code:    "runtime_apply_field_warning",
			Message: fmt.Sprintf("%s (%s): %s", chooseString(field.FieldID, field.StorageKey), chooseString(field.Kind, "unknown"), field.WarningMessage),
			Target:  scope.ScopeID,
		})
	}

	return result, nil
}

func ensureManagedTableTx(ctx context.Context, tx *sql.Tx, scope runtimeApplyScopePlan) error {
	createColumns := []string{
		`"_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`,
		`"tenant_id" bigint NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::bigint`,
		`"_guid" uuid NOT NULL DEFAULT gen_random_uuid()`,
		`"_created_at" timestamptz NOT NULL DEFAULT now()`,
		`"_updated_at" timestamptz NOT NULL DEFAULT now()`,
		`"_row_version" bigint NOT NULL DEFAULT 1`,
	}
	if scope.ParentForeignKey != "" {
		createColumns = append(createColumns, fmt.Sprintf("%s bigint", quoteIdentifier(scope.ParentForeignKey)))
	}

	createStatement := fmt.Sprintf(
		"CREATE TABLE IF NOT EXISTS %s (%s)",
		qualifiedIdentifier(scope.TableName),
		strings.Join(createColumns, ", "),
	)
	if _, err := tx.ExecContext(ctx, createStatement); err != nil {
		return fmt.Errorf("form builder: create runtime table %s: %w", scope.TableName, err)
	}

	if scope.ParentForeignKey != "" {
		if _, err := tx.ExecContext(ctx, fmt.Sprintf(
			"ALTER TABLE %s ADD COLUMN IF NOT EXISTS %s bigint",
			qualifiedIdentifier(scope.TableName),
			quoteIdentifier(scope.ParentForeignKey),
		)); err != nil {
			return fmt.Errorf("form builder: ensure parent fk column on %s: %w", scope.TableName, err)
		}
		if err := ensureIndexTx(ctx, tx, scope.TableName, runtimeDBObjectName("idx", scope.TableName, "tenant_id", scope.ParentForeignKey), false, "tenant_id", scope.ParentForeignKey); err != nil {
			return err
		}
		if err := ensureForeignKeyConstraintTx(ctx, tx, scope.TableName, scope.ParentForeignKey, scope.ParentTableName); err != nil {
			return err
		}
	}

	for _, field := range scope.Fields {
		if !field.Supported || field.MultiValue || field.ColumnName == "" || field.PhysicalType == "" {
			continue
		}
		if _, err := tx.ExecContext(ctx, fmt.Sprintf(
			"ALTER TABLE %s ADD COLUMN IF NOT EXISTS %s %s",
			qualifiedIdentifier(scope.TableName),
			quoteIdentifier(field.ColumnName),
			field.PhysicalType,
		)); err != nil {
			return fmt.Errorf("form builder: ensure runtime column %s.%s: %w", scope.TableName, field.ColumnName, err)
		}
		if field.Kind == "db_lookup" && field.Preset != "db_lookup_value" {
			if err := ensureIndexTx(ctx, tx, scope.TableName, runtimeDBObjectName("idx", scope.TableName, "tenant_id", field.ColumnName), false, "tenant_id", field.ColumnName); err != nil {
				return err
			}
		}
	}

	if err := ensureIndexTx(ctx, tx, scope.TableName, runtimeDBObjectName("idx", scope.TableName, "tenant_id"), false, "tenant_id"); err != nil {
		return err
	}
	if err := ensureIndexTx(ctx, tx, scope.TableName, runtimeDBObjectName("uidx", scope.TableName, "tenant_id", "_guid"), true, "tenant_id", "_guid"); err != nil {
		return err
	}

	return nil
}

func ensureManagedMultiValueTableTx(ctx context.Context, tx *sql.Tx, scope runtimeApplyScopePlan) error {
	createStatement := fmt.Sprintf(
		`CREATE TABLE IF NOT EXISTS %s (
			"_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"tenant_id" bigint NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::bigint,
			%s bigint NOT NULL,
			"field_key" text NOT NULL,
			"value_kind" text NOT NULL,
			"value_key" text,
			"value_label" text,
			"lookup_target_id" bigint,
			"sort_order" bigint NOT NULL DEFAULT 0
		)`,
		qualifiedIdentifier(scope.MultiValueTableName),
		quoteIdentifier(scope.MultiValueOwnerForeignKey),
	)
	if _, err := tx.ExecContext(ctx, createStatement); err != nil {
		return fmt.Errorf("form builder: create runtime multivalue table %s: %w", scope.MultiValueTableName, err)
	}
	if err := ensureIndexTx(ctx, tx, scope.MultiValueTableName, runtimeDBObjectName("idx", scope.MultiValueTableName, "tenant_id"), false, "tenant_id"); err != nil {
		return err
	}
	if err := ensureIndexTx(ctx, tx, scope.MultiValueTableName, runtimeDBObjectName("idx", scope.MultiValueTableName, "tenant_id", scope.MultiValueOwnerForeignKey, "field_key"), false, "tenant_id", scope.MultiValueOwnerForeignKey, "field_key"); err != nil {
		return err
	}
	if err := ensureIndexTx(ctx, tx, scope.MultiValueTableName, runtimeDBObjectName("idx", scope.MultiValueTableName, "tenant_id", "field_key", "lookup_target_id"), false, "tenant_id", "field_key", "lookup_target_id"); err != nil {
		return err
	}
	return nil
}

func ensureScopeDataViewTx(ctx context.Context, tx *sql.Tx, scope runtimeApplyScopePlan) ([]RuntimeApplyLookupOutputResult, error) {
	statement, lookupOutputs := buildRuntimeScopeDataViewSQL(scope)
	if _, err := tx.ExecContext(ctx, statement); err != nil {
		return nil, fmt.Errorf("form builder: create runtime data view %s: %w", scope.DataViewName, err)
	}
	return lookupOutputs, nil
}

func ensureGridViewTx(ctx context.Context, tx *sql.Tx, dataViewName string, gridView runtimeApplyGridViewPlan) error {
	statement := buildRuntimeGridViewSQL(dataViewName, gridView)
	if _, err := tx.ExecContext(ctx, fmt.Sprintf("DROP VIEW IF EXISTS %s", qualifiedIdentifier(gridView.Name))); err != nil {
		return fmt.Errorf("form builder: drop runtime grid view %s: %w", gridView.Name, err)
	}
	if _, err := tx.ExecContext(ctx, statement); err != nil {
		return fmt.Errorf("form builder: create runtime grid view %s: %w", gridView.Name, err)
	}
	return nil
}

func relationExistsTx(ctx context.Context, tx *sql.Tx, relationName string) (bool, error) {
	var exists sql.NullString
	if err := tx.QueryRowContext(ctx, "SELECT to_regclass($1)::text", "public."+relationName).Scan(&exists); err != nil {
		return false, fmt.Errorf("form builder: relation existence check %s: %w", relationName, err)
	}
	return exists.Valid && strings.TrimSpace(exists.String) != "", nil
}

func ensureForeignKeyConstraintTx(ctx context.Context, tx *sql.Tx, tableName string, foreignKey string, parentTableName string) error {
	constraintName := runtimeDBObjectName("fk", tableName, foreignKey, parentTableName)
	var exists bool
	if err := tx.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = $1)", constraintName).Scan(&exists); err != nil {
		return fmt.Errorf("form builder: constraint existence check %s: %w", constraintName, err)
	}
	if exists {
		return nil
	}
	statement := fmt.Sprintf(
		"ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
		qualifiedIdentifier(tableName),
		quoteIdentifier(constraintName),
		quoteIdentifier(foreignKey),
		qualifiedIdentifier(parentTableName),
		quoteIdentifier("_id"),
	)
	if _, err := tx.ExecContext(ctx, statement); err != nil {
		return fmt.Errorf("form builder: add foreign key %s on %s: %w", constraintName, tableName, err)
	}
	return nil
}

func ensureIndexTx(ctx context.Context, tx *sql.Tx, tableName string, indexName string, unique bool, columns ...string) error {
	if len(columns) == 0 {
		return nil
	}
	columnList := make([]string, 0, len(columns))
	for _, column := range columns {
		columnList = append(columnList, quoteIdentifier(column))
	}
	prefix := "CREATE INDEX IF NOT EXISTS"
	if unique {
		prefix = "CREATE UNIQUE INDEX IF NOT EXISTS"
	}
	statement := fmt.Sprintf(
		"%s %s ON %s (%s)",
		prefix,
		quoteIdentifier(indexName),
		qualifiedIdentifier(tableName),
		strings.Join(columnList, ", "),
	)
	if _, err := tx.ExecContext(ctx, statement); err != nil {
		return fmt.Errorf("form builder: ensure index %s on %s: %w", indexName, tableName, err)
	}
	return nil
}

func buildRuntimeScopeDataViewSQL(scope runtimeApplyScopePlan) (string, []RuntimeApplyLookupOutputResult) {
	selectList := make([]string, 0)
	joins := make([]string, 0)
	lookupOutputs := make([]RuntimeApplyLookupOutputResult, 0)

	for _, columnName := range runtimeScopeBaseSelectColumns(scope) {
		selectList = append(selectList, fmt.Sprintf("t.%s AS %s", quoteIdentifier(columnName), quoteIdentifier(columnName)))
	}

	for _, field := range scope.Fields {
		if field.Kind != "db_lookup" || field.Preset == "db_lookup_value" {
			continue
		}
		if field.SelectionMode == "multiple" {
			fieldSelects, fieldOutputs := buildRuntimeMultiValueLookupSelects(scope, field)
			selectList = append(selectList, fieldSelects...)
			lookupOutputs = append(lookupOutputs, fieldOutputs...)
			continue
		}
		fieldJoins, fieldSelects, fieldOutputs := buildRuntimeSingleLookupSelects(field)
		joins = append(joins, fieldJoins...)
		selectList = append(selectList, fieldSelects...)
		lookupOutputs = append(lookupOutputs, fieldOutputs...)
	}

	statement := fmt.Sprintf(
		"CREATE OR REPLACE VIEW %s AS SELECT %s FROM %s t%s",
		qualifiedIdentifier(scope.DataViewName),
		strings.Join(selectList, ", "),
		qualifiedIdentifier(scope.TableName),
		prefixRuntimeJoinClauses(joins),
	)
	return statement, lookupOutputs
}

func buildRuntimeGridViewSQL(dataViewName string, gridView runtimeApplyGridViewPlan) string {
	selectList := make([]string, 0, len(gridView.Projections))
	for _, projection := range gridView.Projections {
		if projection.SourceColumnName == "" || projection.AliasColumnName == "" {
			continue
		}
		if projection.SourceColumnName == projection.AliasColumnName {
			selectList = append(selectList, fmt.Sprintf("v.%s", quoteIdentifier(projection.SourceColumnName)))
			continue
		}
		selectList = append(selectList, fmt.Sprintf(
			"v.%s AS %s",
			quoteIdentifier(projection.SourceColumnName),
			quoteIdentifier(projection.AliasColumnName),
		))
	}
	if len(selectList) == 0 {
		selectList = append(selectList, "v._id")
	}
	return fmt.Sprintf(
		"CREATE OR REPLACE VIEW %s AS SELECT %s FROM %s v",
		qualifiedIdentifier(gridView.Name),
		strings.Join(selectList, ", "),
		qualifiedIdentifier(dataViewName),
	)
}

func runtimeScopeBaseSelectColumns(scope runtimeApplyScopePlan) []string {
	columns := []string{"_id", "tenant_id", "_guid", "_created_at", "_updated_at", "_row_version"}
	if scope.ParentForeignKey != "" {
		columns = append(columns, scope.ParentForeignKey)
	}
	for _, field := range scope.Fields {
		if !field.Supported || field.MultiValue || field.ColumnName == "" {
			continue
		}
		columns = append(columns, field.ColumnName)
	}
	return columns
}

func buildRuntimeSingleLookupSelects(field runtimeApplyFieldPlan) ([]string, []string, []RuntimeApplyLookupOutputResult) {
	if field.ColumnName == "" || field.LookupTargetName == "" || field.LookupTargetIDColumn == "" || len(field.LookupDerivedOutputs) == 0 {
		return nil, nil, nil
	}

	baseAlias := runtimeSQLAlias("lk", field.StorageKey)
	baseJoin := fmt.Sprintf(
		"LEFT JOIN %s %s ON t.%s = %s.%s AND %s",
		qualifiedIdentifier(field.LookupTargetName),
		quoteIdentifier(baseAlias),
		quoteIdentifier(field.ColumnName),
		quoteIdentifier(baseAlias),
		quoteIdentifier(field.LookupTargetIDColumn),
		runtimeLookupBaseJoinTenantCondition(field, "t", baseAlias),
	)

	joins := []string{baseJoin}
	selects := make([]string, 0, len(field.LookupDerivedOutputs))
	outputs := make([]RuntimeApplyLookupOutputResult, 0, len(field.LookupDerivedOutputs))

	switch field.Preset {
	case "contact_lookup":
		companyAlias := runtimeSQLAlias(baseAlias, "company")
		joins = append(joins, fmt.Sprintf(
			"LEFT JOIN %s %s ON %s.%s = %s.%s AND %s.%s = %s.%s",
			qualifiedIdentifier("company"),
			quoteIdentifier(companyAlias),
			quoteIdentifier(baseAlias),
			quoteIdentifier("users_company_id"),
			quoteIdentifier(companyAlias),
			quoteIdentifier("company_id"),
			quoteIdentifier("t"),
			quoteIdentifier("tenant_id"),
			quoteIdentifier(companyAlias),
			quoteIdentifier("company_tenant_id"),
		))
		for _, output := range field.LookupDerivedOutputs {
			selects = append(selects, fmt.Sprintf("%s AS %s", runtimeLookupExpressionForContact(baseAlias, companyAlias, output.OutputKey), quoteIdentifier(output.ColumnName)))
			outputs = append(outputs, RuntimeApplyLookupOutputResult{ColumnName: output.ColumnName, Action: "recreate"})
		}
	case "company_lookup":
		mainCompanyAlias := runtimeSQLAlias(baseAlias, "main_company")
		stateAlias := runtimeSQLAlias(baseAlias, "state")
		joins = append(joins, fmt.Sprintf(
			"LEFT JOIN %s %s ON %s.%s = %s.%s AND %s.%s = %s.%s",
			qualifiedIdentifier("company"),
			quoteIdentifier(mainCompanyAlias),
			quoteIdentifier(baseAlias),
			quoteIdentifier("company_maincomp"),
			quoteIdentifier(mainCompanyAlias),
			quoteIdentifier("company_id"),
			quoteIdentifier("t"),
			quoteIdentifier("tenant_id"),
			quoteIdentifier(mainCompanyAlias),
			quoteIdentifier("company_tenant_id"),
		))
		joins = append(joins, fmt.Sprintf(
			"LEFT JOIN %s %s ON %s.%s = %s.%s",
			qualifiedIdentifier("state"),
			quoteIdentifier(stateAlias),
			quoteIdentifier(baseAlias),
			quoteIdentifier("company_state_id"),
			quoteIdentifier(stateAlias),
			quoteIdentifier("state_id"),
		))
		for _, output := range field.LookupDerivedOutputs {
			selects = append(selects, fmt.Sprintf("%s AS %s", runtimeLookupExpressionForCompany(baseAlias, mainCompanyAlias, stateAlias, output.OutputKey), quoteIdentifier(output.ColumnName)))
			outputs = append(outputs, RuntimeApplyLookupOutputResult{ColumnName: output.ColumnName, Action: "recreate"})
		}
	case "project_lookup":
		companyAlias := runtimeSQLAlias(baseAlias, "company")
		joins = append(joins, fmt.Sprintf(
			"LEFT JOIN %s %s ON %s.%s = %s.%s AND %s.%s = %s.%s",
			qualifiedIdentifier("company"),
			quoteIdentifier(companyAlias),
			quoteIdentifier(baseAlias),
			quoteIdentifier("projects_company_id"),
			quoteIdentifier(companyAlias),
			quoteIdentifier("company_id"),
			quoteIdentifier("t"),
			quoteIdentifier("tenant_id"),
			quoteIdentifier(companyAlias),
			quoteIdentifier("company_tenant_id"),
		))
		for _, output := range field.LookupDerivedOutputs {
			selects = append(selects, fmt.Sprintf("%s AS %s", runtimeLookupExpressionForProject(baseAlias, companyAlias, output.OutputKey), quoteIdentifier(output.ColumnName)))
			outputs = append(outputs, RuntimeApplyLookupOutputResult{ColumnName: output.ColumnName, Action: "recreate"})
		}
	default:
		for _, output := range field.LookupDerivedOutputs {
			selects = append(selects, fmt.Sprintf("%s AS %s", runtimeLookupExpressionForManagedModel(baseAlias, output.OutputKey, field.DisplayFields), quoteIdentifier(output.ColumnName)))
			outputs = append(outputs, RuntimeApplyLookupOutputResult{ColumnName: output.ColumnName, Action: "recreate"})
		}
	}

	return joins, selects, outputs
}

func buildRuntimeMultiValueLookupSelects(scope runtimeApplyScopePlan, field runtimeApplyFieldPlan) ([]string, []RuntimeApplyLookupOutputResult) {
	if scope.MultiValueTableName == "" || scope.MultiValueOwnerForeignKey == "" || len(field.LookupDerivedOutputs) == 0 {
		return nil, nil
	}

	selects := make([]string, 0, len(field.LookupDerivedOutputs))
	outputs := make([]RuntimeApplyLookupOutputResult, 0, len(field.LookupDerivedOutputs))
	mvTable := qualifiedIdentifier(scope.MultiValueTableName)
	fieldKeyLiteral := sqlStringLiteral(field.StorageKey)

	for _, output := range field.LookupDerivedOutputs {
		switch output.OutputKey {
		case "labels":
			selects = append(selects, fmt.Sprintf(
				`(SELECT NULLIF(string_agg(NULLIF(mv.%s, ''), ', ' ORDER BY mv.%s), '')
					FROM %s mv
					WHERE mv.%s = t.%s AND mv.%s = t.%s AND mv.%s = %s) AS %s`,
				quoteIdentifier("value_label"),
				quoteIdentifier("sort_order"),
				mvTable,
				quoteIdentifier("tenant_id"),
				quoteIdentifier("tenant_id"),
				quoteIdentifier(scope.MultiValueOwnerForeignKey),
				quoteIdentifier("_id"),
				quoteIdentifier("field_key"),
				fieldKeyLiteral,
				quoteIdentifier(output.ColumnName),
			))
			outputs = append(outputs, RuntimeApplyLookupOutputResult{ColumnName: output.ColumnName, Action: "recreate"})
		case "count":
			selects = append(selects, fmt.Sprintf(
				`(SELECT COUNT(*)::bigint
					FROM %s mv
					WHERE mv.%s = t.%s AND mv.%s = t.%s AND mv.%s = %s) AS %s`,
				mvTable,
				quoteIdentifier("tenant_id"),
				quoteIdentifier("tenant_id"),
				quoteIdentifier(scope.MultiValueOwnerForeignKey),
				quoteIdentifier("_id"),
				quoteIdentifier("field_key"),
				fieldKeyLiteral,
				quoteIdentifier(output.ColumnName),
			))
			outputs = append(outputs, RuntimeApplyLookupOutputResult{ColumnName: output.ColumnName, Action: "recreate"})
		}
	}

	return selects, outputs
}

func prefixRuntimeJoinClauses(joins []string) string {
	if len(joins) == 0 {
		return ""
	}
	return " " + strings.Join(joins, " ")
}

func runtimeLookupBaseJoinTenantCondition(field runtimeApplyFieldPlan, baseAlias string, targetAlias string) string {
	targetTenantColumn := "tenant_id"
	switch field.Preset {
	case "contact_lookup":
		targetTenantColumn = "users_tenant_id"
	case "company_lookup":
		targetTenantColumn = "company_tenant_id"
	case "project_lookup":
		targetTenantColumn = "projects_tenant_id"
	default:
		if field.LookupTargetKind == "view" {
			targetTenantColumn = "tenant_id"
		}
	}
	return fmt.Sprintf(
		"%s.%s = %s.%s",
		quoteIdentifier(baseAlias),
		quoteIdentifier("tenant_id"),
		quoteIdentifier(targetAlias),
		quoteIdentifier(targetTenantColumn),
	)
}

func runtimeLookupExpressionForContact(userAlias string, companyAlias string, outputKey string) string {
	switch outputKey {
	case "label":
		return runtimeConcatWS(" ", runtimeNullableTextColumn(userAlias, "users_firstname"), runtimeNullableTextColumn(userAlias, "users_lastname"))
	case "company_name":
		return runtimeNullableTextColumn(companyAlias, "company_name")
	case "company_id":
		return fmt.Sprintf("%s.%s", quoteIdentifier(userAlias), quoteIdentifier("users_company_id"))
	case "title":
		return runtimeNullableTextColumn(userAlias, "users_title")
	case "phone":
		return fmt.Sprintf("COALESCE(%s, %s)", runtimeNullableTextColumn(userAlias, "users_phone"), runtimeNullableTextColumn(userAlias, "users_mobilephone"))
	default:
		return "NULL"
	}
}

func runtimeLookupExpressionForCompany(companyAlias string, mainCompanyAlias string, stateAlias string, outputKey string) string {
	switch outputKey {
	case "label":
		return runtimeNullableTextColumn(companyAlias, "company_name")
	case "type":
		return runtimeNullableTextColumn(companyAlias, "company_type")
	case "main_company_name":
		return runtimeNullableTextColumn(mainCompanyAlias, "company_name")
	case "state":
		return fmt.Sprintf("COALESCE(%s, %s.%s::text)", runtimeNullableTextColumn(stateAlias, "state_name"), quoteIdentifier(companyAlias), quoteIdentifier("company_state_id"))
	default:
		return "NULL"
	}
}

func runtimeLookupExpressionForProject(projectAlias string, companyAlias string, outputKey string) string {
	switch outputKey {
	case "label":
		return runtimeConcatWS(", ", runtimeNullableTextColumn(projectAlias, "projects_num"), runtimeNullableTextColumn(projectAlias, "projects_name"))
	case "num":
		return runtimeNullableTextColumn(projectAlias, "projects_num")
	case "name":
		return runtimeNullableTextColumn(projectAlias, "projects_name")
	case "company_name":
		return runtimeNullableTextColumn(companyAlias, "company_name")
	default:
		return "NULL"
	}
}

func runtimeLookupExpressionForManagedModel(targetAlias string, outputKey string, displayFields []string) string {
	if outputKey != "label" {
		return "NULL"
	}
	parts := make([]string, 0, len(displayFields))
	for _, fieldKey := range displayFields {
		normalizedFieldKey := strings.TrimSpace(fieldKey)
		if normalizedFieldKey == "" {
			continue
		}
		if normalizedFieldKey == "doc_id" {
			parts = append(parts, fmt.Sprintf("%s.%s::text", quoteIdentifier(targetAlias), quoteIdentifier("_id")))
			continue
		}
		parts = append(parts, runtimeNullableTextColumn(targetAlias, normalizedFieldKey))
	}
	if len(parts) == 0 {
		parts = append(parts, fmt.Sprintf("%s.%s::text", quoteIdentifier(targetAlias), quoteIdentifier("_id")))
	}
	return runtimeConcatWS(" ", parts...)
}

func runtimeConcatWS(separator string, expressions ...string) string {
	filtered := make([]string, 0, len(expressions))
	for _, expression := range expressions {
		if strings.TrimSpace(expression) == "" {
			continue
		}
		filtered = append(filtered, expression)
	}
	if len(filtered) == 0 {
		return "NULL"
	}
	return fmt.Sprintf("NULLIF(concat_ws(%s, %s), '')", sqlStringLiteral(separator), strings.Join(filtered, ", "))
}

func runtimeNullableTextColumn(alias string, column string) string {
	return fmt.Sprintf("NULLIF(%s.%s::text, '')", quoteIdentifier(alias), quoteIdentifier(column))
}

func runtimeSQLAlias(parts ...string) string {
	raw := normalizeStableKey(strings.Join(parts, "_"))
	if raw == "" {
		return "lk"
	}
	return strings.ReplaceAll(raw, "-", "_")
}

func sqlStringLiteral(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

func filterRuntimeMultiValueFields(fields []runtimeApplyFieldPlan) []runtimeApplyFieldPlan {
	out := make([]runtimeApplyFieldPlan, 0)
	for _, field := range fields {
		if field.MultiValue {
			out = append(out, field)
		}
	}
	return out
}

func chooseRuntimeRelationAction(existed bool) string {
	if existed {
		return "reuse"
	}
	return "create"
}

func chooseRuntimeViewAction(existed bool) string {
	if existed {
		return "recreate"
	}
	return "create"
}

func quoteIdentifier(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}

func qualifiedIdentifier(name string) string {
	return `"public".` + quoteIdentifier(name)
}

func runtimeDBObjectName(prefix string, parts ...string) string {
	raw := prefix + "_" + strings.Join(parts, "_")
	raw = strings.ReplaceAll(raw, "-", "_")
	raw = strings.ToLower(raw)
	if len(raw) <= 63 {
		return raw
	}
	sum := sha1.Sum([]byte(raw))
	suffix := hex.EncodeToString(sum[:4])
	trimmed := raw[:63-len(suffix)-1]
	return trimmed + "_" + suffix
}
