package store

func AgentCapabilities() []AgentCapability {
	capabilities := []AgentCapability{
		{
			Role:              "maestro",
			DisplayName:       "Maestro",
			Type:              "orchestrator",
			Purpose:           "Intake, routing, lifecycle ownership, gates, reconciliation, and closeout.",
			WritesCode:        "tiny direct only",
			WritesArtifacts:   "yes",
			BrowserAccess:     "optional",
			ReleaseAccess:     "no",
			HighRiskAccess:    "approval only",
			DefaultStages:     []string{"planning", "closeout"},
			RecommendedSkills: []string{"feature-slicing", "test-planning", "security-check"},
			ApprovalTriggers:  []string{"auth", "tenant", "migration", "secrets", "release", "destructive"},
			FormalChainRole:   true,
			SourceContract:    "maestro/docs/agent-roles.md",
			NextHandoff:       "bounded task packet or specialist stage assignment",
		},
		{
			Role:              "charlie",
			DisplayName:       "Charlie",
			Type:              "research",
			Purpose:           "Codebase and docs research, observed facts, risks, and change points.",
			WritesCode:        "no",
			WritesArtifacts:   "research only",
			BrowserAccess:     "no",
			ReleaseAccess:     "no",
			HighRiskAccess:    "read-only",
			DefaultStages:     []string{"research"},
			RecommendedSkills: []string{"safe-refactor", "migration-check", "security-check"},
			FormalChainRole:   true,
			SourceContract:    "maestro/docs/agent-roles.md",
			NextHandoff:       "research handoff with facts, risks, and change points",
		},
		{
			Role:              "grant",
			DisplayName:       "Grant",
			Type:              "audit",
			Purpose:           "Brief, plan, dependency, risk, and acceptance audit before execution.",
			WritesCode:        "no",
			WritesArtifacts:   "audit only",
			BrowserAccess:     "no",
			ReleaseAccess:     "no",
			HighRiskAccess:    "read-only",
			DefaultStages:     []string{"brief_audit"},
			RecommendedSkills: []string{"security-check", "migration-check", "test-planning"},
			FormalChainRole:   true,
			SourceContract:    "maestro/docs/agent-roles.md",
			NextHandoff:       "audit decision: accept, revise, or block",
		},
		{
			Role:              "mason",
			DisplayName:       "Mason",
			Type:              "implementation",
			Purpose:           "Scoped implementation across frontend, backend, docs, and tests.",
			WritesCode:        "scoped",
			WritesArtifacts:   "assigned attempt",
			BrowserAccess:     "if assigned",
			ReleaseAccess:     "no",
			HighRiskAccess:    "approval only",
			DefaultStages:     []string{"implementation"},
			RecommendedSkills: []string{"ui-designer", "safe-refactor", "test-planning"},
			ApprovalTriggers:  []string{"auth", "tenant", "migration", "secrets"},
			FormalChainRole:   true,
			SourceContract:    "maestro/docs/agent-roles.md",
			NextHandoff:       "attempt handoff with changed files, commands, evidence, and risks",
		},
		{
			Role:              "scout",
			DisplayName:       "Scout",
			Type:              "verification",
			Purpose:           "Checks, CI, Storybook, browser, migrations, and security gates.",
			WritesCode:        "limited",
			WritesArtifacts:   "evidence only",
			BrowserAccess:     "yes",
			ReleaseAccess:     "no",
			HighRiskAccess:    "check only",
			DefaultStages:     []string{"verification"},
			RecommendedSkills: []string{"browser-visual-review", "test-planning", "migration-check"},
			FormalChainRole:   true,
			SourceContract:    "maestro/docs/agent-roles.md",
			NextHandoff:       "verification report and attached evidence",
		},
		{
			Role:              "lens",
			DisplayName:       "Lens",
			Type:              "review",
			Purpose:           "Read-only diff, evidence, acceptance, and risk review.",
			WritesCode:        "no",
			WritesArtifacts:   "review only",
			BrowserAccess:     "no",
			ReleaseAccess:     "no",
			HighRiskAccess:    "read-only",
			DefaultStages:     []string{"review"},
			RecommendedSkills: []string{"security-check", "test-planning"},
			FormalChainRole:   true,
			SourceContract:    "maestro/docs/agent-roles.md",
			NextHandoff:       "review finding list and accept/revise/block recommendation",
		},
		{
			Role:              "release",
			DisplayName:       "Release",
			Type:              "release",
			Purpose:           "Deployment, release packaging, workflow dispatch, and rollback notes.",
			WritesCode:        "limited",
			WritesArtifacts:   "release record",
			BrowserAccess:     "optional",
			ReleaseAccess:     "yes",
			HighRiskAccess:    "approval only",
			DefaultStages:     []string{"release"},
			RecommendedSkills: []string{"security-check", "migration-check"},
			ApprovalTriggers:  []string{"release", "production", "rollback"},
			FormalChainRole:   true,
			SourceContract:    "maestro/docs/agent-roles.md",
			NextHandoff:       "release evidence, links, and rollback notes",
		},
		{
			Role:              "scribe",
			DisplayName:       "Scribe",
			Type:              "closeout",
			Purpose:           "Run record, evidence summary, final artifact packet, and residual risks.",
			WritesCode:        "docs/artifacts only",
			WritesArtifacts:   "closeout",
			BrowserAccess:     "no",
			ReleaseAccess:     "no",
			HighRiskAccess:    "no",
			DefaultStages:     []string{"closeout"},
			RecommendedSkills: []string{"docs-memory-update"},
			FormalChainRole:   true,
			SourceContract:    "maestro/docs/agent-roles.md",
			NextHandoff:       "closeout summary and portable evidence record",
		},
		{
			Role:              "archivist",
			DisplayName:       "Archivist",
			Type:              "memory audit",
			Purpose:           "Semantic docs and ai-memory consistency auditor.",
			WritesCode:        "docs/memory only",
			WritesArtifacts:   "memory audit",
			BrowserAccess:     "no",
			ReleaseAccess:     "no",
			HighRiskAccess:    "no",
			DefaultStages:     []string{"memory_audit"},
			RecommendedSkills: []string{"docs-memory-update"},
			FormalChainRole:   true,
			SourceContract:    "maestro/docs/agent-roles.md",
			NextHandoff:       "memory drift findings or accepted memory update",
		},
		{
			Role:              "atlas",
			DisplayName:       "Atlas",
			Type:              "independent helper",
			Purpose:           "Personal helper/router outside the formal Maestro chain.",
			WritesCode:        "optional direct",
			WritesArtifacts:   "optional",
			BrowserAccess:     "optional",
			ReleaseAccess:     "no",
			HighRiskAccess:    "approval only",
			DefaultStages:     []string{},
			RecommendedSkills: []string{"ui-designer", "browser-visual-review", "safe-refactor"},
			FormalChainRole:   false,
			IndependentHelper: true,
			SourceContract:    "maestro/docs/agent-roles.md",
			NextHandoff:       "owner-facing quick helper result, not a Maestro lifecycle transition",
		},
	}
	for i := range capabilities {
		if capabilities[i].DefaultStages == nil {
			capabilities[i].DefaultStages = []string{}
		}
		if capabilities[i].RecommendedSkills == nil {
			capabilities[i].RecommendedSkills = []string{}
		}
		if capabilities[i].ApprovalTriggers == nil {
			capabilities[i].ApprovalTriggers = []string{}
		}
	}
	return capabilities
}

func AgentNames() []string {
	capabilities := AgentCapabilities()
	names := make([]string, 0, len(capabilities))
	for _, capability := range capabilities {
		names = append(names, capability.Role)
	}
	return names
}
