import {
  PLATFORM_BUILDER_SCHEMA_VERSION,
  parseDraftSnapshot,
  type DraftSnapshot,
} from "@platform/platform-builder-core";

const builderDraftSeedInput = {
  childCollections: [
    {
      childEntityId: "entity.corrective-action",
      id: "collection.incident.actions",
      key: "incident.actions",
      label: "Corrective actions",
      parentEntityId: "entity.incident",
      relationId: "relation.corrective-action.incident",
    },
  ],
  draftId: "draft.northwind-platform-builder",
  entities: [
    {
      description: "Workspace incidents captured from tenant operations.",
      id: "entity.incident",
      key: "incident",
      name: "Incident",
      pluralName: "Incidents",
    },
    {
      description: "Follow-up work attached to an incident record.",
      id: "entity.corrective-action",
      key: "corrective_action",
      name: "Corrective Action",
      pluralName: "Corrective Actions",
    },
    {
      description: "Facility reference data used by operational records.",
      id: "entity.site",
      key: "site",
      name: "Site",
      pluralName: "Sites",
    },
  ],
  fields: [
    {
      dataType: "string",
      description: "Primary incident title.",
      entityId: "entity.incident",
      id: "field.incident.title",
      key: "title",
      label: "Title",
      required: true,
    },
    {
      dataType: "enum",
      description: "Current incident workflow state.",
      entityId: "entity.incident",
      id: "field.incident.status",
      key: "status",
      label: "Status",
      optionSetId: "optionset.incident.status",
      required: true,
    },
    {
      dataType: "date",
      description: "Date when the incident was observed.",
      entityId: "entity.incident",
      id: "field.incident.occurred-on",
      key: "occurred_on",
      label: "Occurred on",
    },
    {
      dataType: "string",
      description: "Named owner responsible for follow-up.",
      entityId: "entity.incident",
      id: "field.incident.owner",
      key: "owner",
      label: "Owner",
    },
    {
      dataType: "relation",
      description: "Linked operating site.",
      entityId: "entity.incident",
      id: "field.incident.site",
      key: "site",
      label: "Site",
      relationId: "relation.incident.site",
      required: true,
    },
    {
      dataType: "string",
      description: "Short corrective action summary.",
      entityId: "entity.corrective-action",
      id: "field.corrective-action.summary",
      key: "summary",
      label: "Summary",
      required: true,
    },
    {
      dataType: "date",
      description: "Expected completion date.",
      entityId: "entity.corrective-action",
      id: "field.corrective-action.due-date",
      key: "due_date",
      label: "Due date",
    },
    {
      dataType: "relation",
      description: "Owning incident.",
      entityId: "entity.corrective-action",
      id: "field.corrective-action.incident",
      key: "incident",
      label: "Incident",
      relationId: "relation.corrective-action.incident",
      required: true,
    },
    {
      dataType: "boolean",
      description: "Flag for completion.",
      entityId: "entity.corrective-action",
      id: "field.corrective-action.completed",
      key: "completed",
      label: "Completed",
    },
    {
      dataType: "string",
      description: "Reference site name.",
      entityId: "entity.site",
      id: "field.site.name",
      key: "name",
      label: "Name",
      required: true,
    },
    {
      dataType: "enum",
      description: "Operating region for the site.",
      entityId: "entity.site",
      id: "field.site.region",
      key: "region",
      label: "Region",
      optionSetId: "optionset.site.region",
    },
    {
      dataType: "boolean",
      description: "Whether the site is active.",
      entityId: "entity.site",
      id: "field.site.active",
      key: "is_active",
      label: "Active",
      required: true,
    },
  ],
  lastValidationReport: {
    issues: [],
    valid: true,
  },
  navigationNodes: [
    {
      icon: "layers",
      id: "nav.group.operations",
      label: "Operations",
      order: 0,
      type: "group",
    },
    {
      channels: ["web"],
      icon: "document-list",
      id: "nav.item.incidents",
      label: "Incidents",
      order: 1,
      parentId: "nav.group.operations",
      routeKey: "incidents",
      target: {
        kind: "view",
        viewId: "view.incident.list",
      },
      type: "item",
      visibilityPolicyId: "policy.builder.admin",
    },
    {
      channels: ["web"],
      icon: "building-office",
      id: "nav.item.sites",
      label: "Sites",
      order: 2,
      parentId: "nav.group.operations",
      routeKey: "sites",
      target: {
        kind: "view",
        viewId: "view.site.list",
      },
      type: "item",
      visibilityPolicyId: "policy.builder.admin",
    },
  ],
  optionSets: [
    {
      description: "Incident lifecycle values.",
      id: "optionset.incident.status",
      key: "incident.status",
      name: "Incident status",
      options: [
        {
          label: "New",
          value: "new",
        },
        {
          label: "In review",
          value: "in_review",
        },
        {
          label: "Closed",
          value: "closed",
        },
      ],
    },
    {
      description: "Available tenant operating regions.",
      id: "optionset.site.region",
      key: "site.region",
      name: "Site region",
      options: [
        {
          label: "North",
          value: "north",
        },
        {
          label: "South",
          value: "south",
        },
        {
          label: "West",
          value: "west",
        },
      ],
    },
  ],
  policies: [
    {
      actionPolicies: [
        {
          actionKey: "builder.publish",
          allowed: true,
        },
      ],
      description: "Builder administration policy for the demo tenant.",
      fieldPolicies: [
        {
          access: "editable",
          fieldId: "field.incident.title",
        },
        {
          access: "editable",
          fieldId: "field.incident.status",
        },
      ],
      id: "policy.builder.admin",
      key: "builder.admin",
      name: "Builder admin",
      roleKeys: ["tenant.admin"],
    },
  ],
  relations: [
    {
      id: "relation.incident.site",
      key: "incident.site",
      kind: "many-to-one",
      label: "Incident site",
      sourceEntityId: "entity.incident",
      sourceFieldId: "field.incident.site",
      targetEntityId: "entity.site",
    },
    {
      id: "relation.corrective-action.incident",
      key: "corrective_action.incident",
      kind: "many-to-one",
      label: "Corrective action incident",
      sourceEntityId: "entity.corrective-action",
      sourceFieldId: "field.corrective-action.incident",
      targetEntityId: "entity.incident",
    },
  ],
  schemaVersion: PLATFORM_BUILDER_SCHEMA_VERSION,
  semanticRoles: [
    {
      entityId: "entity.incident",
      fieldId: "field.incident.title",
      id: "semantic-role.incident.title",
      role: "title",
    },
    {
      entityId: "entity.incident",
      fieldId: "field.incident.status",
      id: "semantic-role.incident.status",
      role: "status",
    },
    {
      entityId: "entity.incident",
      fieldId: "field.incident.occurred-on",
      id: "semantic-role.incident.date",
      role: "date",
    },
    {
      entityId: "entity.incident",
      fieldId: "field.incident.owner",
      id: "semantic-role.incident.owner",
      role: "owner",
    },
    {
      entityId: "entity.corrective-action",
      fieldId: "field.corrective-action.summary",
      id: "semantic-role.corrective-action.title",
      role: "title",
    },
    {
      entityId: "entity.corrective-action",
      fieldId: "field.corrective-action.due-date",
      id: "semantic-role.corrective-action.date",
      role: "date",
    },
    {
      entityId: "entity.site",
      fieldId: "field.site.name",
      id: "semantic-role.site.title",
      role: "title",
    },
  ],
  snapshotKind: "draft",
  updatedAt: "2026-03-20T14:30:00.000Z",
  views: [
    {
      channel: "web",
      description: "Primary incident list used by the builder navigation summary.",
      entityId: "entity.incident",
      id: "view.incident.list",
      isDefault: true,
      key: "incident.list",
      nodes: [
        {
          id: "viewnode.incident.list.root",
          kind: "section",
          slots: {
            body: ["viewnode.incident.list.text"],
          },
          title: "Incident list",
        },
        {
          id: "viewnode.incident.list.text",
          kind: "text",
          text: "List placeholder for incident records.",
        },
      ],
      rootNodeId: "viewnode.incident.list.root",
      title: "Incident List",
      type: "list",
    },
    {
      channel: "web",
      description: "Default incident detail form.",
      entityId: "entity.incident",
      id: "view.incident.detail",
      isDefault: true,
      key: "incident.detail",
      nodes: [
        {
          id: "viewnode.incident.detail.root",
          kind: "section",
          slots: {
            body: [
              "viewnode.incident.detail.title",
              "viewnode.incident.detail.status",
              "viewnode.incident.detail.site",
            ],
          },
          title: "Incident detail",
        },
        {
          fieldId: "field.incident.title",
          id: "viewnode.incident.detail.title",
          kind: "field",
          widgetKey: "text-input",
        },
        {
          fieldId: "field.incident.status",
          id: "viewnode.incident.detail.status",
          kind: "field",
          widgetKey: "status-select",
        },
        {
          fieldId: "field.incident.site",
          id: "viewnode.incident.detail.site",
          kind: "field",
          widgetKey: "entity-select",
        },
      ],
      rootNodeId: "viewnode.incident.detail.root",
      title: "Incident Detail",
      type: "detail",
    },
    {
      channel: "web",
      description: "Detail form for corrective actions.",
      entityId: "entity.corrective-action",
      id: "view.corrective-action.detail",
      key: "corrective_action.detail",
      nodes: [
        {
          id: "viewnode.corrective-action.detail.root",
          kind: "section",
          slots: {
            body: [
              "viewnode.corrective-action.detail.summary",
              "viewnode.corrective-action.detail.due-date",
            ],
          },
          title: "Corrective action detail",
        },
        {
          fieldId: "field.corrective-action.summary",
          id: "viewnode.corrective-action.detail.summary",
          kind: "field",
          widgetKey: "text-input",
        },
        {
          fieldId: "field.corrective-action.due-date",
          id: "viewnode.corrective-action.detail.due-date",
          kind: "field",
          widgetKey: "date-input",
        },
      ],
      rootNodeId: "viewnode.corrective-action.detail.root",
      title: "Corrective Action Detail",
      type: "detail",
    },
    {
      channel: "web",
      description: "Reference list for sites.",
      entityId: "entity.site",
      id: "view.site.list",
      key: "site.list",
      nodes: [
        {
          id: "viewnode.site.list.root",
          kind: "section",
          slots: {
            body: ["viewnode.site.list.text"],
          },
          title: "Site list",
        },
        {
          id: "viewnode.site.list.text",
          kind: "text",
          text: "List placeholder for sites.",
        },
      ],
      rootNodeId: "viewnode.site.list.root",
      title: "Site List",
      type: "list",
    },
  ],
  workflows: [
    {
      actionBindings: [
        {
          event: "onSubmit",
          handlerKey: "notifications.request-review",
          id: "workflow-action.incident.review-notify",
        },
      ],
      entityId: "entity.incident",
      id: "workflow.incident.lifecycle",
      key: "incident.lifecycle",
      name: "Incident lifecycle",
      statuses: [
        {
          id: "workflow-status.incident.new",
          isInitial: true,
          key: "new",
          label: "New",
        },
        {
          id: "workflow-status.incident.in-review",
          key: "in_review",
          label: "In review",
        },
        {
          id: "workflow-status.incident.closed",
          key: "closed",
          label: "Closed",
        },
      ],
      transitions: [
        {
          actionBindingIds: ["workflow-action.incident.review-notify"],
          fromStatusId: "workflow-status.incident.new",
          id: "workflow-transition.incident.submit",
          key: "submit_for_review",
          label: "Submit for review",
          toStatusId: "workflow-status.incident.in-review",
        },
        {
          fromStatusId: "workflow-status.incident.in-review",
          id: "workflow-transition.incident.close",
          key: "close_incident",
          label: "Close incident",
          toStatusId: "workflow-status.incident.closed",
        },
      ],
    },
  ],
} satisfies DraftSnapshot;

export const builderDraftSeed = parseDraftSnapshot(builderDraftSeedInput);
