-- ============================================
-- Golden Schema Bundle: tenant_schema_full.sql
-- ============================================
--
-- Generated: 2026-03-30T12:57:51-04:00
-- Source: migrations from migrations/postgres/archive, migrations/postgres/tenant
--
-- Checksum: 67f0d27b1c230c034a0dbacb112ccdc0707f44e635d44821fa3a47bf1fbabcc8
--
-- Migrations included:
--   - 000_tenant_baseline.sql
-- ============================================


-- ============================================
-- Migration: 000_tenant_baseline.sql
-- ============================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  IF to_jsonb(NEW) ? 'updated_at' THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object('updated_at', now()));
  ELSIF to_jsonb(NEW) ? (TG_TABLE_NAME || '_updated_at') THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_TABLE_NAME || '_updated_at', now()));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Full legacy-shaped users table.
-- Auth reads email/phone/access/admin/activity directly from this table.
CREATE TABLE IF NOT EXISTS users (
  users_tenant_id    BIGINT NOT NULL,
  users_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  users_rowstamp     BYTEA,
  users_tourread     BOOLEAN,
  users_access       BOOLEAN,
  users_act          BOOLEAN NOT NULL DEFAULT true,
  users_active       BOOLEAN GENERATED ALWAYS AS (COALESCE(users_act, false)) STORED,
  users_admin        BOOLEAN,
  users_company_id   BIGINT,
  users_date         TIMESTAMPTZ,
  users_dob          DATE,
  users_email        CITEXT,
  users_firstname    TEXT,
  users_lastname     TEXT,
  users_middlename   TEXT,
  users_mobilephone  TEXT,
  users_pager        TEXT,
  users_password     TEXT,
  users_phone        TEXT,
  users_title        TEXT,
  users_username     TEXT,
  users_supervisor   BIGINT,
  users_foreman      BIGINT,
  users_desc         TEXT,
  users_hiredate     DATE,
  users_rehiredate   DATE,
  users_lastwork     DATE,
  users_termwork     DATE,
  users_sex          TEXT,
  users_num          TEXT,
  users_pcode        TEXT,
  users_last         TIMESTAMPTZ,
  users_lastmodule   TEXT,
  users_lastaction   TEXT,
  users_lastpage     TEXT,
  users_lastwizard   TEXT,
  users_timezone     TEXT,
  users_address      TEXT,
  users_city         TEXT,
  users_state        TEXT,
  users_zip          TEXT,
  users_ssn          TEXT,
  users_pwddate      TIMESTAMPTZ,
  users_terms        BOOLEAN,
  users_pwdchanged   INTEGER,
  users_demo         BOOLEAN,
  users_status       TEXT,
  users_reason       TEXT,
  users_occupation   TEXT,
  users_salery       NUMERIC(14,2),
  users_saleryper    NUMERIC(14,2),
  users_systemid     TEXT,
  users_auth         INTEGER,
  users_sysid        TEXT,
  users_site         TEXT,
  users_usersid      TEXT,
  users_etsadmin     INTEGER,
  users_1027_super   BIGINT,
  users_1042_dep     TEXT,
  users_1042_super2  BIGINT,
  users_1042_super3  BIGINT,
  users_1042_super1  BIGINT,
  users_wccode       TEXT,
  users_wcdesc       TEXT,
  users_pushapp      TEXT,
  users_pushacc      TEXT,
  users_covidcheck   BOOLEAN,
  users_honorific    TEXT,
  users_pincode      TEXT,
  users_codes        JSONB,
  users_guid         UUID NOT NULL DEFAULT gen_random_uuid(),
  users_created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  users_updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (users_tenant_id, users_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_tenant_guid
  ON users(users_tenant_id, users_guid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_tenant_email_ci
  ON users(users_tenant_id, users_email)
  WHERE users_email IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_mobilephone
  ON users(users_tenant_id, users_mobilephone);
CREATE INDEX IF NOT EXISTS idx_users_phone
  ON users(users_tenant_id, users_phone);
CREATE INDEX IF NOT EXISTS idx_users_company_id
  ON users(users_tenant_id, users_company_id);
CREATE INDEX IF NOT EXISTS idx_users_act
  ON users(users_tenant_id, users_act);
CREATE INDEX IF NOT EXISTS idx_users_access
  ON users(users_tenant_id, users_access);
CREATE INDEX IF NOT EXISTS idx_users_admin
  ON users(users_tenant_id, users_admin);
CREATE INDEX IF NOT EXISTS idx_users_firstname
  ON users(users_tenant_id, users_firstname);
CREATE INDEX IF NOT EXISTS idx_users_lastname
  ON users(users_tenant_id, users_lastname);
CREATE INDEX IF NOT EXISTS idx_users_middlename
  ON users(users_tenant_id, users_middlename);
CREATE INDEX IF NOT EXISTS idx_users_auth
  ON users(users_tenant_id, users_auth);
CREATE INDEX IF NOT EXISTS idx_users_etsadmin
  ON users(users_tenant_id, users_etsadmin);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_users_updated_at') THEN
    CREATE TRIGGER trg_users_updated_at
      BEFORE UPDATE ON users
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_users_tenant ON users;
CREATE POLICY p_users_tenant ON users
  USING (users_tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (users_tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS companytype (
  companytype_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  companytype_tenant_id  BIGINT NOT NULL,
  companytype_guid       UUID NOT NULL DEFAULT gen_random_uuid(),
  companytype_name       TEXT,
  companytype_risk       TEXT,
  companytype_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  companytype_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_companytype_tenant_guid
  ON companytype(companytype_tenant_id, companytype_guid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_companytype_tenant_name
  ON companytype(companytype_tenant_id, companytype_name);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_companytype_updated_at') THEN
    CREATE TRIGGER trg_companytype_updated_at
      BEFORE UPDATE ON companytype
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE companytype ENABLE ROW LEVEL SECURITY;
ALTER TABLE companytype FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_companytype_tenant ON companytype;
CREATE POLICY p_companytype_tenant ON companytype
  USING (companytype_tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (companytype_tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS company (
  company_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_tenant_id    BIGINT NOT NULL,
  company_guid         UUID NOT NULL DEFAULT gen_random_uuid(),
  company_act          BOOLEAN NOT NULL DEFAULT true,
  company_address      TEXT,
  company_address2     TEXT,
  company_city         TEXT,
  company_comppol      TEXT,
  company_fax          TEXT,
  company_name         TEXT,
  company_phone        TEXT,
  company_state_id     BIGINT,
  company_unempol      TEXT,
  company_url          TEXT,
  company_type         TEXT,
  company_zip          TEXT,
  company_email        CITEXT,
  company_maincomp     BIGINT,
  company_desc         TEXT,
  company_vendor       TEXT,
  company_tax          TEXT,
  company_liaison      TEXT,
  company_key          TEXT,
  company_premium      INTEGER,
  company_safpol       TEXT,
  company_timezone     TEXT,
  company_demo         BOOLEAN NOT NULL DEFAULT false,
  company_contactname  TEXT,
  company_naic         TEXT,
  company_product      TEXT,
  company_num          TEXT,
  company_recgroup     TEXT,
  company_geo          TEXT,
  company_connumber    TEXT,
  company_joined       DATE,
  company_created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  company_updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_company_tenant_guid
  ON company(company_tenant_id, company_guid);
CREATE INDEX IF NOT EXISTS ix_company_tenant_name ON company(company_tenant_id, company_name);
CREATE INDEX IF NOT EXISTS ix_company_tenant_act ON company(company_tenant_id, company_act);
CREATE INDEX IF NOT EXISTS ix_company_tenant_email ON company(company_tenant_id, company_email);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_company_updated_at') THEN
    CREATE TRIGGER trg_company_updated_at
      BEFORE UPDATE ON company
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE company ENABLE ROW LEVEL SECURITY;
ALTER TABLE company FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_company_tenant ON company;
CREATE POLICY p_company_tenant ON company
  USING (company_tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (company_tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS projects (
  projects_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  projects_tenant_id          BIGINT NOT NULL,
  projects_guid               UUID NOT NULL DEFAULT gen_random_uuid(),
  projects_user               BIGINT,
  projects_date               TIMESTAMPTZ,
  projects_act                BOOLEAN NOT NULL DEFAULT true,
  projects_address            TEXT,
  projects_address2           TEXT,
  projects_city               TEXT,
  projects_phone              TEXT,
  projects_fax                TEXT,
  projects_mail               CITEXT,
  projects_company_id         BIGINT,
  projects_contractor         BIGINT,
  projects_datebegin          DATE,
  projects_dateend            DATE,
  projects_desc               TEXT,
  projects_info               TEXT,
  projects_name               TEXT,
  projects_num                TEXT,
  projects_projectsstatus_id  BIGINT,
  projects_state_id           BIGINT,
  projects_url                TEXT,
  projects_value              NUMERIC(14,2),
  projects_zip                TEXT,
  projects_ocip               TEXT,
  projects_medfac8            INTEGER,
  projects_medfac24           INTEGER,
  projects_glocip             TEXT,
  projects_glbid              TEXT,
  projects_wcocip             TEXT,
  projects_wcbid              TEXT,
  projects_status             TEXT,
  projects_year               TEXT,
  projects_pc                 TEXT,
  projects_rate               TEXT,
  projects_type               TEXT,
  projects_detailer           BIGINT,
  projects_estimator          BIGINT,
  projects_salesp             BIGINT,
  projects_sov                TEXT,
  projects_estnum             TEXT,
  projects_estweight          TEXT,
  projects_fiunit             TEXT,
  projects_averate            TEXT,
  projects_camount            TEXT,
  projects_detunit            TEXT,
  projects_mrg                TEXT,
  projects_gamount            TEXT,
  projects_gmanhr             TEXT,
  projects_grate              TEXT,
  projects_lettersent         DATE,
  projects_complete           DATE,
  projects_contact            BIGINT,
  projects_ptvender           BIGINT,
  projects_sub                TEXT,
  projects_ve                 TEXT,
  projects_payroll            TEXT,
  projects_applied            DATE,
  projects_approved           DATE,
  projects_pinnam             TEXT,
  projects_pinncost           TEXT,
  projects_pinnmarg           TEXT,
  projects_pinnpr             TEXT,
  projects_pcode              TEXT,
  projects_ohp                TEXT,
  projects_prman              BIGINT,
  projects_psuper             BIGINT,
  projects_psafrep            BIGINT,
  projects_tar                BIGINT,
  projects_subcontr           BIGINT,
  projects_demo               BOOLEAN NOT NULL DEFAULT false,
  projects_naicscode          TEXT,
  projects_inddesc            TEXT,
  projects_size               TEXT,
  projects_avg                TEXT,
  projects_geocode            TEXT,
  projects_created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  projects_updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_projects_tenant_guid
  ON projects(projects_tenant_id, projects_guid);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_name ON projects(projects_tenant_id, projects_name);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_num ON projects(projects_tenant_id, projects_num);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_company ON projects(projects_tenant_id, projects_company_id);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_user ON projects(projects_tenant_id, projects_user);
CREATE INDEX IF NOT EXISTS ix_projects_tenant_act ON projects(projects_tenant_id, projects_act);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_projects_updated_at') THEN
    CREATE TRIGGER trg_projects_updated_at
      BEFORE UPDATE ON projects
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_projects_tenant ON projects;
CREATE POLICY p_projects_tenant ON projects
  USING (projects_tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (projects_tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS projectsaccess (
  projectsaccess_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  projectsaccess_tenant_id   BIGINT NOT NULL,
  projectsaccess_projects_id BIGINT,
  projectsaccess_users_id    BIGINT,
  projectsaccess_role        TEXT,
  projectsaccess_created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  projectsaccess_updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_projectsaccess_tenant_role
  ON projectsaccess(projectsaccess_tenant_id, projectsaccess_projects_id, projectsaccess_users_id, projectsaccess_role);
CREATE INDEX IF NOT EXISTS ix_projectsaccess_tenant_project
  ON projectsaccess(projectsaccess_tenant_id, projectsaccess_projects_id);
CREATE INDEX IF NOT EXISTS ix_projectsaccess_tenant_user
  ON projectsaccess(projectsaccess_tenant_id, projectsaccess_users_id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_projectsaccess_updated_at') THEN
    CREATE TRIGGER trg_projectsaccess_updated_at
      BEFORE UPDATE ON projectsaccess
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE projectsaccess ENABLE ROW LEVEL SECURITY;
ALTER TABLE projectsaccess FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_projectsaccess_tenant ON projectsaccess;
CREATE POLICY p_projectsaccess_tenant ON projectsaccess
  USING (projectsaccess_tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (projectsaccess_tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS events (
  events_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  events_tenant_id   BIGINT NOT NULL,
  events_date        DATE,
  events_event       TEXT NOT NULL,
  events_module      TEXT,
  events_record      BIGINT,
  events_table       TEXT,
  events_text        TEXT,
  events_time        TIMESTAMPTZ,
  events_timezone    TEXT,
  events_users_id    BIGINT,
  events_actor_guid  UUID,
  events_users_ip    INET,
  events_to          TEXT,
  events_subject     TEXT,
  events_body        TEXT,
  events_data        JSONB NOT NULL DEFAULT '{}'::jsonb,
  events_files       JSONB,
  events_urls        JSONB,
  events_created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  events_updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (events_created_at, events_id)
) PARTITION BY RANGE (events_created_at);

CREATE TABLE IF NOT EXISTS events_default PARTITION OF events DEFAULT;

DO $$
DECLARE
  quarter_base DATE := date_trunc('quarter', current_date)::date;
  part_start   DATE;
  part_end     DATE;
  part_name    TEXT;
BEGIN
  FOR i IN -1..8 LOOP
    part_start := (quarter_base + make_interval(months => i * 3))::date;
    part_end := (part_start + INTERVAL '3 months')::date;
    part_name := format('events_y%s_q%s',
      EXTRACT(YEAR FROM part_start)::int,
      EXTRACT(QUARTER FROM part_start)::int
    );

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I PARTITION OF events FOR VALUES FROM (%L) TO (%L)',
      part_name,
      part_start,
      part_end
    );
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS ix_events_tenant_created
  ON events(events_tenant_id, events_created_at DESC);
CREATE INDEX IF NOT EXISTS ix_events_tenant_event_created
  ON events(events_tenant_id, events_event, events_created_at DESC);
CREATE INDEX IF NOT EXISTS ix_events_tenant_actor_created
  ON events(events_tenant_id, events_actor_guid, events_created_at DESC)
  WHERE events_actor_guid IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_events_tenant_module_created
  ON events(events_tenant_id, events_module, events_created_at DESC);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_events_tenant ON events;
CREATE POLICY p_events_tenant ON events
  USING (events_tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (events_tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS mails (
  mails_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mails_tenant_id   BIGINT NOT NULL,
  mails_users_id    BIGINT,
  mails_date        TIMESTAMPTZ,
  mails_timezone    TEXT,
  mails_from        TEXT,
  mails_to          TEXT,
  mails_cc          TEXT,
  mails_bcc         TEXT,
  mails_subject     TEXT,
  mails_body        TEXT,
  mails_who         TEXT,
  mails_files       JSONB,
  mails_urls        JSONB,
  mails_table       TEXT,
  mails_recid       BIGINT,
  mails_created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  mails_updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_mails_tenant_user ON mails(mails_tenant_id, mails_users_id);
CREATE INDEX IF NOT EXISTS ix_mails_tenant_recid ON mails(mails_tenant_id, mails_recid);
CREATE INDEX IF NOT EXISTS ix_mails_tenant_date ON mails(mails_tenant_id, mails_date DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_mails_updated_at') THEN
    CREATE TRIGGER trg_mails_updated_at
      BEFORE UPDATE ON mails
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE mails ENABLE ROW LEVEL SECURITY;
ALTER TABLE mails FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_mails_tenant ON mails;
CREATE POLICY p_mails_tenant ON mails
  USING (mails_tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (mails_tenant_id = current_setting('app.tenant_id', true)::bigint);

CREATE TABLE IF NOT EXISTS public_code (
  code        TEXT PRIMARY KEY,
  tenant_id   BIGINT NOT NULL,
  resource_id UUID,
  expires_at  TIMESTAMPTZ,
  metadata    JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_public_code_tenant ON public_code(tenant_id);
CREATE INDEX IF NOT EXISTS idx_public_code_expires ON public_code(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_public_code_resource ON public_code(resource_id) WHERE resource_id IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_public_code_updated_at') THEN
    CREATE TRIGGER trg_public_code_updated_at
      BEFORE UPDATE ON public_code
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS notification_template (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id  BIGINT,
  kind       TEXT NOT NULL CHECK (kind IN ('email', 'sms')),
  key        TEXT NOT NULL,
  locale     TEXT NOT NULL DEFAULT 'default',
  subject    TEXT,
  html       TEXT,
  text       TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_template_global
  ON notification_template(kind, key, locale)
  WHERE tenant_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_template_tenant
  ON notification_template(tenant_id, kind, key, locale)
  WHERE tenant_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_notification_template_tenant ON notification_template(tenant_id);
CREATE INDEX IF NOT EXISTS ix_notification_template_key ON notification_template(kind, key);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_notification_template_updated_at') THEN
    CREATE TRIGGER trg_notification_template_updated_at
      BEFORE UPDATE ON notification_template
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

INSERT INTO notification_template
(tenant_id, kind, key, locale, subject, html, text)
SELECT
  NULL, 'email', 'otp', 'default',
  'Our OTP Code',
  '<p>Hello!</p><p>Your OTP code: <b>{{ code }}</b></p><p>Code valid for {{ ttl }} minutes.</p>',
  'Hello!\nYour OTP code: {{ code }}\nCode valid for {{ ttl }} minutes.'
WHERE NOT EXISTS (
  SELECT 1
    FROM notification_template
   WHERE tenant_id IS NULL
     AND kind = 'email'
     AND key = 'otp'
     AND locale = 'default'
);

INSERT INTO notification_template
(tenant_id, kind, key, locale, subject, html, text)
SELECT
  NULL, 'sms', 'otp', 'default',
  NULL,
  NULL,
  'Your code {{ code }}, valid for {{ ttl }} minutes.'
WHERE NOT EXISTS (
  SELECT 1
    FROM notification_template
   WHERE tenant_id IS NULL
     AND kind = 'sms'
     AND key = 'otp'
     AND locale = 'default'
);

COMMIT;


-- ============================================
-- Bundle End
-- ============================================
-- Total migrations: 1
-- Versions: 000_tenant_baseline
-- ============================================
