import type {
  RuntimeFormLabels,
  RuntimeFormResolvedLabels,
} from "./runtime-form-types";

const defaultRuntimeFormLabels: RuntimeFormResolvedLabels = {
  backToList: "Back to list",
  booleanNo: "No",
  booleanYes: "Yes",
  catalogEmpty: "No catalog options found.",
  catalogGroupOther: "Other",
  catalogLoadError: "Could not load catalog options.",
  catalogLoading: "Loading catalog...",
  catalogNoSelection: "No catalog item selected",
  catalogOpen: "Open catalog",
  catalogRetry: "Retry",
  catalogSearchPlaceholder: "Search catalog",
  catalogSelect: "Select",
  createModeInfo: "Complete the required fields to create this record. Changes will save automatically after it is created.",
  createTitle: "Start new record",
  editModeInfo: "This form saves changes automatically as you work. You can continue working with it later.",
  editTitle: "Edit record",
  emptyValue: "-",
  finish: "Finish",
  finishBackInfoActionTemplate: "When you click \"{{finish}}\", the form will run the configured finish action.",
  finishBackInfoCreateBackTemplate: "If the record has not been created yet, \"{{back}}\" will ask before discarding entered data; after creation, it keeps the current status.",
  finishBackInfoEditBackTemplate: "When you click \"{{back}}\", the form will keep the current status.",
  finishBackInfoStatusTemplate: "When you click \"{{finish}}\", the form will have the status \"{{status}}\".",
  generatedAccordionItemTitle: "Item",
  generatedOutputLabel: "Output",
  generatedSubformTitle: "Subform",
  generatedTabTitle: "Tab",
  invalidEmailError: "Please enter a valid email address.",
  invalidGeoPointError: "Please enter a valid geographic point.",
  invalidMaskError: "Please enter a value that matches the required format.",
  invalidPhoneError: "Please enter a valid phone number.",
  invalidUrlError: "Please enter a valid URL.",
  geoPointLocating: "Loading...",
  geoPointMap: "Map",
  geoPointPlaceholder: "Coordinates will be captured automatically",
  loadMore: "Load more",
  noOptions: "No options",
  onlineFormTitle: "Online Form",
  requiredError: "This field is required.",
  search: "Search",
  saveStates: {
    dirty: "Unsaved",
    error: "Needs attention",
    idle: "Ready",
    saved: "Saved",
    saving: "Saving",
  },
  selectPlaceholder: "Select...",
  selectValuesPlaceholder: "Select values",
  subformAdd: "Add",
  subformDelete: "Delete",
  subformEdit: "Edit",
  subformEmpty: "No records yet.",
  validationFillField: "Please fill field: \"{{field}}\"",
  validationFillFieldCorrectly: "Please fill field correctly: \"{{field}}\"",
};

export function resolveRuntimeFormLabels(labels?: RuntimeFormLabels): RuntimeFormResolvedLabels {
  return {
    ...defaultRuntimeFormLabels,
    ...labels,
    saveStates: {
      ...defaultRuntimeFormLabels.saveStates,
      ...labels?.saveStates,
    },
  };
}
